/**
 * Default algorithm parameters and mutable app settings.
 */
(() => {
  window.Vectura = window.Vectura || {};
  const MM_PER_INCH = 25.4;
  const normalizeDocumentUnits = (value) => (`${value || ''}`.trim().toLowerCase() === 'imperial' ? 'imperial' : 'metric');
  const getDocumentUnitLabel = (units) => (normalizeDocumentUnits(units) === 'imperial' ? 'in' : 'mm');
  const mmToDocumentUnits = (value, units) => {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) return 0;
    return normalizeDocumentUnits(units) === 'imperial' ? numeric / MM_PER_INCH : numeric;
  };
  const documentUnitsToMm = (value, units) => {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) return 0;
    return normalizeDocumentUnits(units) === 'imperial' ? numeric * MM_PER_INCH : numeric;
  };
  const getDocumentUnitPrecision = (units, fallback = null) => {
    if (Number.isFinite(fallback)) return fallback;
    return normalizeDocumentUnits(units) === 'imperial' ? 2 : 1;
  };
  const getDocumentUnitStep = (units, fallback = null) => {
    if (Number.isFinite(fallback)) return fallback;
    return normalizeDocumentUnits(units) === 'imperial' ? 0.01 : 0.1;
  };
  const formatDocumentLength = (valueMm, units, options = {}) => {
    const {
      precision = null,
      includeUnit = true,
      trimTrailingZeros = false,
      spaceBeforeUnit = false,
    } = options;
    const resolvedUnits = normalizeDocumentUnits(units);
    const decimals = getDocumentUnitPrecision(resolvedUnits, precision);
    const displayValue = mmToDocumentUnits(valueMm, resolvedUnits);
    let text = Number(displayValue).toFixed(decimals);
    if (trimTrailingZeros && text.includes('.')) {
      text = text.replace(/\.?0+$/, '');
    }
    if (!includeUnit) return text;
    const unit = getDocumentUnitLabel(resolvedUnits);
    return `${text}${spaceBeforeUnit ? ' ' : ''}${unit}`;
  };
  window.Vectura.UnitUtils = {
    MM_PER_INCH,
    normalizeDocumentUnits,
    getDocumentUnitLabel,
    mmToDocumentUnits,
    documentUnitsToMm,
    getDocumentUnitPrecision,
    getDocumentUnitStep,
    formatDocumentLength,
  };
  window.Vectura.THEMES = {
    dark: {
      id: 'dark',
      label: 'Dark',
      colorScheme: 'dark',
      metaThemeColor: '#09090b',
      documentBg: '#121214',
      pen1Color: '#ffffff',
      cssVars: {
        '--vectura-bg-rgb': '9 9 11',
        '--vectura-panel-rgb': '24 24 27',
        '--vectura-border-rgb': '39 39 42',
        '--vectura-text-rgb': '228 228 231',
        '--vectura-muted-rgb': '113 113 122',
        '--vectura-accent-rgb': '250 250 250',
        '--vectura-danger-rgb': '239 68 68',
        '--color-bg': '#09090b',
        '--color-panel': '#18181b',
        '--color-border': '#27272a',
        '--color-border-strong': '#3f3f46',
        '--color-border-hover': '#52525b',
        '--color-text': '#e4e4e7',
        '--color-text-soft': '#a1a1aa',
        '--color-muted': '#71717a',
        '--color-formula-text': '#d4d4d8',
        '--color-accent': '#fafafa',
        '--color-surface': '#0f0f12',
        '--color-surface-alt': '#111113',
        '--color-control': '#141417',
        '--color-control-hover': '#1f1f23',
        '--color-read-surface': '#18181b',
        '--color-workspace': '#121214',
        '--color-touch-border': '#2f3036',
        '--color-mobile-handle-bg': 'rgba(9, 9, 11, 0.94)',
        '--shadow-panel': '0 12px 30px rgba(0, 0, 0, 0.4)',
        '--shadow-float': '0 10px 30px rgba(0, 0, 0, 0.35)',
        '--render-canvas': '#121214',
        '--render-shadow': 'rgba(0, 0, 0, 0.5)',
        '--render-paper-outline': '#333333',
        '--render-frame-stroke': 'rgba(255,255,255,0.08)',
        '--render-guide-faint': 'rgba(248, 250, 252, 0.75)',
        '--render-selection-handle-fill': '#111827',
        '--render-selection-handle-stroke': '#f8fafc',
        '--render-cursor-stroke': 'white',
        '--render-marquee-stroke': 'rgba(148, 163, 184, 0.7)',
        '--render-marquee-fill': 'rgba(148, 163, 184, 0.12)',
        '--render-direct-stroke': '#22d3ee',
        '--render-direct-handle-line': 'rgba(34, 211, 238, 0.65)',
        '--render-direct-handle-fill': '#0f172a',
        '--render-underlay-fill': 'rgba(15, 23, 42, 0.92)',
        '--render-underlay-stroke': 'rgba(15, 23, 42, 1)',
        '--designer-grid-bg': '#0f1116',
        '--designer-grid-line': 'rgba(148,163,184,0.14)',
        '--designer-fill-active': 'rgba(56, 189, 248, 0.1)',
        '--designer-fill-inactive': 'rgba(34, 211, 238, 0.05)',
        '--designer-stroke-active': '#67e8f9',
        '--designer-stroke-inactive': 'rgba(103, 232, 249, 0.55)',
        '--designer-shading-stroke': 'rgba(125, 211, 252, 0.6)',
        '--designer-control-line': 'rgba(34, 211, 238, 0.55)',
        '--designer-control-fill': '#0f172a',
        '--designer-control-anchor': '#22d3ee',
        '--designer-control-handle': '#67e8f9',
        '--plotter-bg': '#101115',
        '--plotter-path-base': 'rgba(113,113,122,0.35)',
        '--plotter-head': '#fafafa',
      },
    },
    light: {
      id: 'light',
      label: 'Light',
      colorScheme: 'light',
      metaThemeColor: '#f5f5f5',
      documentBg: '#ffffff',
      pen1Color: '#000000',
      cssVars: {
        '--vectura-bg-rgb': '243 244 246',
        '--vectura-panel-rgb': '229 231 235',
        '--vectura-border-rgb': '212 212 216',
        '--vectura-text-rgb': '24 24 27',
        '--vectura-muted-rgb': '82 82 91',
        '--vectura-accent-rgb': '9 9 11',
        '--vectura-danger-rgb': '220 38 38',
        '--color-bg': '#f3f4f6',
        '--color-panel': '#e5e7eb',
        '--color-border': '#d4d4d8',
        '--color-border-strong': '#a1a1aa',
        '--color-border-hover': '#71717a',
        '--color-text': '#18181b',
        '--color-text-soft': '#3f3f46',
        '--color-muted': '#52525b',
        '--color-formula-text': '#52525b',
        '--color-accent': '#09090b',
        '--color-surface': '#f4f5f8',
        '--color-surface-alt': '#eceef2',
        '--color-control': '#ffffff',
        '--color-control-hover': '#f8fafc',
        '--color-read-surface': '#f8fafc',
        '--color-workspace': '#dadde3',
        '--color-touch-border': '#cbd5e1',
        '--color-mobile-handle-bg': 'rgba(243, 244, 246, 0.96)',
        '--shadow-panel': '0 12px 30px rgba(15, 23, 42, 0.14)',
        '--shadow-float': '0 10px 30px rgba(15, 23, 42, 0.16)',
        '--render-canvas': '#dadde3',
        '--render-shadow': 'rgba(15, 23, 42, 0.18)',
        '--render-paper-outline': '#a1a1aa',
        '--render-frame-stroke': 'rgba(24,24,27,0.12)',
        '--render-guide-faint': 'rgba(24, 24, 27, 0.45)',
        '--render-selection-handle-fill': '#ffffff',
        '--render-selection-handle-stroke': '#18181b',
        '--render-cursor-stroke': '#18181b',
        '--render-marquee-stroke': 'rgba(71, 85, 105, 0.55)',
        '--render-marquee-fill': 'rgba(71, 85, 105, 0.10)',
        '--render-direct-stroke': '#0284c7',
        '--render-direct-handle-line': 'rgba(14, 165, 233, 0.55)',
        '--render-direct-handle-fill': '#ffffff',
        '--render-underlay-fill': 'rgba(255, 255, 255, 0.95)',
        '--render-underlay-stroke': 'rgba(255, 255, 255, 1)',
        '--designer-grid-bg': '#f4f5f7',
        '--designer-grid-line': 'rgba(71,85,105,0.14)',
        '--designer-fill-active': 'rgba(14, 165, 233, 0.12)',
        '--designer-fill-inactive': 'rgba(14, 165, 233, 0.06)',
        '--designer-stroke-active': '#0284c7',
        '--designer-stroke-inactive': 'rgba(2, 132, 199, 0.5)',
        '--designer-shading-stroke': 'rgba(14, 165, 233, 0.55)',
        '--designer-control-line': 'rgba(14, 165, 233, 0.45)',
        '--designer-control-fill': '#ffffff',
        '--designer-control-anchor': '#0284c7',
        '--designer-control-handle': '#38bdf8',
        '--plotter-bg': '#f4f5f7',
        '--plotter-path-base': 'rgba(82,82,91,0.35)',
        '--plotter-head': '#18181b',
      },
    },
    lark: {
      id: 'lark',
      label: 'Lark',
      colorScheme: 'dark',
      metaThemeColor: '#09090b',
      documentBg: '#ffffff',
      pen1Color: '#000000',
      cssVars: {
        '--vectura-bg-rgb': '9 9 11',
        '--vectura-panel-rgb': '24 24 27',
        '--vectura-border-rgb': '39 39 42',
        '--vectura-text-rgb': '228 228 231',
        '--vectura-muted-rgb': '113 113 122',
        '--vectura-accent-rgb': '250 250 250',
        '--vectura-danger-rgb': '239 68 68',
        '--color-bg': '#09090b',
        '--color-panel': '#18181b',
        '--color-border': '#27272a',
        '--color-border-strong': '#3f3f46',
        '--color-border-hover': '#52525b',
        '--color-text': '#e4e4e7',
        '--color-text-soft': '#a1a1aa',
        '--color-muted': '#71717a',
        '--color-formula-text': '#d4d4d8',
        '--color-accent': '#fafafa',
        '--color-surface': '#0f0f12',
        '--color-surface-alt': '#111113',
        '--color-control': '#141417',
        '--color-control-hover': '#1f1f23',
        '--color-read-surface': '#18181b',
        '--color-workspace': '#121214',
        '--color-touch-border': '#2f3036',
        '--color-mobile-handle-bg': 'rgba(9, 9, 11, 0.94)',
        '--shadow-panel': '0 12px 30px rgba(0, 0, 0, 0.4)',
        '--shadow-float': '0 10px 30px rgba(0, 0, 0, 0.35)',
        '--render-canvas': '#dadde3',
        '--render-shadow': 'rgba(15, 23, 42, 0.18)',
        '--render-paper-outline': '#a1a1aa',
        '--render-frame-stroke': 'rgba(24,24,27,0.12)',
        '--render-guide-faint': 'rgba(24, 24, 27, 0.45)',
        '--render-selection-handle-fill': '#ffffff',
        '--render-selection-handle-stroke': '#18181b',
        '--render-cursor-stroke': '#18181b',
        '--render-marquee-stroke': 'rgba(71, 85, 105, 0.55)',
        '--render-marquee-fill': 'rgba(71, 85, 105, 0.10)',
        '--render-direct-stroke': '#0284c7',
        '--render-direct-handle-line': 'rgba(14, 165, 233, 0.55)',
        '--render-direct-handle-fill': '#ffffff',
        '--render-underlay-fill': 'rgba(255, 255, 255, 0.95)',
        '--render-underlay-stroke': 'rgba(255, 255, 255, 1)',
        '--designer-grid-bg': '#0f1116',
        '--designer-grid-line': 'rgba(148,163,184,0.14)',
        '--designer-fill-active': 'rgba(56, 189, 248, 0.1)',
        '--designer-fill-inactive': 'rgba(34, 211, 238, 0.05)',
        '--designer-stroke-active': '#67e8f9',
        '--designer-stroke-inactive': 'rgba(103, 232, 249, 0.55)',
        '--designer-shading-stroke': 'rgba(125, 211, 252, 0.6)',
        '--designer-control-line': 'rgba(34, 211, 238, 0.55)',
        '--designer-control-fill': '#0f172a',
        '--designer-control-anchor': '#22d3ee',
        '--designer-control-handle': '#67e8f9',
        '--plotter-bg': '#f4f5f7',
        '--plotter-path-base': 'rgba(82,82,91,0.35)',
        '--plotter-head': '#18181b',
      },
    },
  };
  window.Vectura.ALGO_DEFAULTS = {
    wavetable: {
      lineStructure: 'horizontal',
      lines: 130,
      noiseType: 'simplex',
      noiseImageId: '',
      noiseImageName: '',
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 9,
          zoom: 0.02,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          polygonZoomReference: 0.02,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      imageAlgo: 'luma',
      imageThreshold: 0.5,
      imagePosterize: 5,
      imageBlur: 0,
      amplitude: 9,
      zoom: 0.02,
      tilt: 0,
      gap: 1.0,
      freq: 1.0,
      lineOffset: 180,
      continuity: 'none',
      dampenExtremes: false,
      overlapPadding: 0,
      flatCaps: false,
      edgeFadeMode: 'both',
      edgeFade: 0,
      edgeFadeThreshold: 0,
      edgeFadeFeather: 0,
      noiseAngle: 0,
      verticalFade: 0,
      verticalFadeThreshold: 0,
      verticalFadeFeather: 0,
      verticalFadeMode: 'both',
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    rings: {
      label: 'Rings',
      preset: 'custom',
      rings: 15,
      centerDiameter: 0,
      outerDiameter: 140,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 10,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          applyMode: 'topdown',
          ringDrift: 0.5,
          ringRadius: 100,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.001,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      amplitude: 10,
      noiseScale: 0.01,
      noiseOffsetX: 0,
      noiseOffsetY: 0,
      noiseLayer: 0.5,
      noiseRadius: 100,
      gap: 1.2,
      gapCurveStart: 1,
      gapCurveEnd: 1,
      spacingVariance: 0,
      barkRings: 5,
      barkGap: 0.5,
      breakCount: 0,
      breakRadiusMin: 0,
      breakRadiusMax: 100,
      breakLengthVariance: 0,
      breakNoiseSeed: 0,
      breakWidthMin: 2,
      breakWidthMax: 6,
      breakWidthVariance: 0,
      centerDrift: 0,
      biasStrength: 0,
      biasAngle: 0,
      rayCount: 0,
      rayLength: 2.5,
      rayMinLength: 0.5,
      rayMaxLength: 2.5,
      rayInnerFraction: 0.15,
      raySeed: 0,
      rayLengthVariance: 0,
      knotCount: 0,
      knotMinSize: 1,
      knotMaxSize: 5,
      knotSeed: 0,
      knotIntensity: 0.6,
      knotSpread: 30,
      knotStrengthVariance: 0,
      knotDirection: 'outer',
      knotSize: 5,
      knotSizeVariance: 0,
      vMarkCount: 0,
      vMarkDepth: 5,
      vMarkSpread: 1,
      vMarkSize: 50,
      vMarkSeed: 0,
      scarCount: 0,
      scarDepth: 3,
      scarWidth: 5,
      scarSize: 8,
      scarSeed: 0,
      thickRingCount: 0,
      thickRingDensity: 0.85,
      thickRingWidth: 3,
      thickRingSeed: 0,
      crackCount: 0,
      crackDepth: 0.5,
      crackSpread: 4,
      crackNoise: 0.3,
      crackSeed: 0,
      crackOutline: false,
      barkType: 'smooth',
      barkRoughness: 4,
      barkRoughnessConfinement: 0.5,
      barkFreq: 3,
      barkFurrowCount: 14,
      barkFurrowDepth: 5,
      barkFurrowWidth: 0.12,
      barkPlateCount: 10,
      barkPlateRelief: 3.5,
      barkPlateVariance: 0.4,
      barkPaperStrips: 7,
      barkPaperPeel: 2.5,
      barkPaperJitter: 0.3,
      barkFiberCount: 28,
      barkFiberAmplitude: 2.5,
      barkFiberPhaseShift: 0.25,
      barkScaleColumns: 18,
      barkScaleRelief: 3,
      barkScaleTaper: 0.6,
      barkCrackDensity: 8,
      barkCrackDepth: 5,
      barkCrackWidth: 0.07,
      barkLenticleCount: 18,
      barkLenticleDepth: 3,
      barkLenticleWidth: 0.12,
      barkWeaveFreq: 9,
      barkWeaveAmplitude: 2,
      barkWeaveAngle: 45,
      offsetX: 0,
      offsetY: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    topo: {
      label: 'Topo',
      resolution: 120,
      levels: 30,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.003,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 3,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.003,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      noiseScale: 0.003,
      noiseOffsetX: 0,
      noiseOffsetY: 0,
      octaves: 3,
      lacunarity: 2.0,
      gain: 0.5,
      sensitivity: 1.0,
      thresholdOffset: 0,
      mappingMode: 'marching',
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    petalisDesigner: {
      label: 'Petalis',
      preset: 'custom',
      petalProfile: 'teardrop',
      petalScale: 32,
      petalWidthRatio: 1,
      petalLengthRatio: 1,
      petalSizeRatio: 1,
      leafSidePos: 0.45,
      leafSideWidth: 1,
      leafBaseHandle: 0.35,
      leafSideHandle: 0.4,
      leafTipHandle: 0.35,
      designerOuter: null,
      designerInner: null,
      petalSteps: 32,
      layering: true,
      anchorToCenter: 'central',
      anchorRadiusRatio: 1,
      tipSharpness: 1,
      tipTwist: 0,
      tipCurl: 0,
      baseFlare: 0,
      basePinch: 0,
      edgeWaveAmp: 0.05,
      edgeWaveFreq: 3,
      radiusScale: 0.2,
      radiusScaleCurve: 1.2,
      sizeJitter: 0.12,
      rotationJitter: 6,
      count: 40,
      countJitter: 0.1,
      ringMode: 'dual',
      innerCount: 20,
      outerCount: 20,
      ringSplit: 0.45,
      innerOuterLock: false,
      designerSymmetry: 'none',
      designerInnerSymmetry: 'none',
      designerOuterSymmetry: 'none',
      petalVisualizerViewStyle: 'overlay',
      profileTransitionPosition: 50,
      profileTransitionFeather: 0,
      ringOffset: 12,
      spiralMode: 'golden',
      customAngle: 137.5,
      spiralTightness: 1.1,
      radialGrowth: 0.05,
      spiralStart: 0,
      spiralEnd: 1,
      angularDrift: 0,
      driftStrength: 0.1,
      driftNoise: 0.2,
      driftNoises: [],
      centerSizeMorph: 0,
      centerSizeCurve: 1.2,
      centerShapeMorph: 0.2,
      centerProfile: 'oval',
      centerCurlBoost: 0,
      centerWaveBoost: 0.2,
      budMode: false,
      budRadius: 0.15,
      budTightness: 0.5,
      centerType: 'disk',
      centerRadius: 8,
      centerDensity: 20,
      centerFalloff: 0.6,
      centerFilamentNoises: [],
      centerRing: false,
      centerRingRadius: 14,
      centerRingDensity: 16,
      centerConnectors: false,
      connectorCount: 60,
      connectorLength: 10,
      connectorJitter: 0.3,
      shadings: [],
      useDesignerShapeOnly: true,
      petalModifiers: [],
      centerModifiers: [
        {
          id: 'mod-1',
          enabled: false,
          type: 'ripple',
          amount: 2,
          frequency: 6,
          scale: 0.2,
          noises: [],
          offsetX: 0,
          offsetY: 0,
          radius: 10,
          seed: 0,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    rainfall: {
      label: 'Rainfall',
      count: 210,
      traceLength: 120,
      traceStep: 3,
      turbulence: 0.25,
      lengthJitter: 0,
      stepJitter: 0,
      gustStrength: 0,
      rainfallAngle: 150,
      angleJitter: 0,
      windAngle: 180,
      windStrength: 0,
      dropSize: 3,
      dropSizeJitter: 0,
      dropRotate: 0,
      dropShape: 'none',
      dropFill: 'none',
      fillDensity: 1,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillDotSize: 1.0,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillRadialCentralDensity: 1.0,
      fillRadialOuterDiameter: 1.0,
      fillAxes: 3,
      widthMultiplier: 1,
      thickeningMode: 'parallel',
      trailBreaks: 'drop',
      breakSpacing: 10,
      breakLengthJitter: 0,
      breakWidthJitter: 0,
      breakRandomness: 0,
      silhouetteId: '',
      silhouetteName: '',
      silhouetteWidth: 200,
      silhouetteHeight: 200,
      silhouetteTilesX: 1,
      silhouetteTilesY: 1,
      silhouetteSpacing: 0,
      silhouetteOffsetX: 0,
      silhouetteOffsetY: 0,
      silhouetteInvert: false,
      noiseApply: 'trails',
      noises: [],
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    flowfield: {
      flowMode: 'angle',
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 2,
          lacunarity: 2.0,
          gain: 0.5,
          fieldMode: 'angle',
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.01,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      noiseScale: 0.01,
      lacunarity: 2.0,
      gain: 0.5,
      density: 1200,
      stepLen: 5,
      maxSteps: 200,
      force: 1.0,
      angleOffset: 0,
      chaos: 0.1,
      octaves: 2,
      minSteps: 2,
      minLength: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    lissajous: {
      freqX: 3,
      freqY: 2,
      damping: 0.001,
      phase: 1.5,
      resolution: 200,
      scale: 0.8,
      truncateStart: 0,
      truncateEnd: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
      closeLines: false,
    },
    pattern: {
      label: 'Pattern',
      patternFilter: 'lines',
      patternId: window.Vectura?.PATTERNS?.[0]?.id || '',
      scale: 1,
      originX: 0,
      originY: 0,
      tileSpacingX: 0,
      tileSpacingY: 0,
      tileMethod: 'grid',
      penMapping: {},
      removeSeams: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
      tileEdgeCurves: false,
      patternFills: [],
      fillSensitivity: 2.0,
      patternCustomPaths: [],
    },
    harmonograph: {
      label: 'Harmonograph',
      renderMode: 'line',
      samples: 6000,
      duration: 30,
      scale: 0.35,
      paperRotation: 0,
      dashLength: 4,
      dashGap: 2,
      pointStride: 4,
      pointSize: 0.4,
      segmentStride: 6,
      segmentLength: 6,
      gapSize: 0,
      gapOffset: 0,
      gapRandomness: 0,
      widthMultiplier: 1,
      thickeningMode: 'parallel',
      loopDrift: 0,
      settleThreshold: 0,
      settleWindow: 24,
      showPendulumGuides: false,
      pendulumGuideColor: '#f59e0b',
      pendulumGuideWidth: 0.25,
      pendulums: [
        {
          id: 'pend-1',
          enabled: true,
          ampX: 100,
          ampY: 100,
          phaseX: 90,
          phaseY: 0,
          damp: 0.002,
          freq: 3,
          micro: 0.01,
        },
        {
          id: 'pend-2',
          enabled: true,
          ampX: 100,
          ampY: 100,
          phaseX: 0,
          phaseY: 90,
          damp: 0.002,
          freq: 2,
          micro: 0.02,
        },
        {
          id: 'pend-3',
          enabled: true,
          ampX: 50,
          ampY: -50,
          phaseX: 270,
          phaseY: 0,
          damp: 0.002,
          freq: 3,
          micro: -0.01,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    spiral: {
      loops: 10,
      res: 100,
      noiseAmp: 10,
      noiseFreq: 0.1,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'turbulence',
          blend: 'add',
          amplitude: 10,
          zoom: 0.1,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          applyMode: 'topdown',
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          polygonZoomReference: 0.1,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      startR: 5,
      angleOffset: 0,
      pulseAmp: 0,
      pulseFreq: 2,
      axisSnap: true,
      close: false,
      closeFeather: 0.5,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    grid: {
      rows: 20,
      cols: 20,
      distortion: 10,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.05,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 1,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.05,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseScale: 0.05,
      type: 'warp',
      chaos: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    phylla: {
      count: 500,
      spacing: 5,
      angleStr: 137.5,
      divergence: 1.0,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.05,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 1,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.05,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseInf: 0,
      dotSize: 1.0,
      shapeType: 'circle',
      sides: 6,
      sideJitter: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    boids: {
      count: 100,
      steps: 100,
      speed: 2,
      sepDist: 10,
      alignDist: 20,
      cohDist: 20,
      force: 0.05,
      sepWeight: 1.2,
      alignWeight: 1.0,
      cohWeight: 0.9,
      mode: 'birds',
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    attractor: {
      type: 'lorenz',
      iter: 1200,
      scale: 3,
      sigma: 10,
      rho: 28,
      beta: 2.66,
      dt: 0.01,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    hyphae: {
      sources: 2,
      steps: 50,
      branchProb: 0.05,
      angleVar: 0.5,
      segLen: 3,
      maxBranches: 1000,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    shapePack: {
      label: 'Shape Pack',
      shape: 'circle',
      count: 500,
      minR: 2,
      maxR: 20,
      padding: 1,
      attempts: 200,
      segments: 32,
      rotationStep: 0,
      perspectiveType: 'none',
      perspective: 0,
      perspectiveX: 0,
      perspectiveY: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    terrain: {
      label: 'Terrain',
      preset: 'custom',
      perspectiveMode: 'one-point',
      horizonHeight: 50,
      vanishingPointX: 50,
      vpLeftX: 20,
      vpRightX: 80,
      isoAngle: 30,
      depthCompression: 60,
      depthScale: 80,
      depthSlices: 80,
      xResolution: 240,
      occlusion: true,
      mountainAmplitude: 40,
      mountainFrequency: 0.008,
      mountainOctaves: 5,
      mountainLacunarity: 2.0,
      mountainGain: 0.5,
      peakSharpness: 2.0,
      valleyCount: 2,
      valleyDepth: 30,
      valleyWidth: 20,
      valleyShape: 0.4,
      valleyMeander: 40,
      riversEnabled: false,
      riverCount: 2,
      riverWidth: 3,
      riverDepth: 8,
      riverMeander: 50,
      oceansEnabled: false,
      waterLevel: 20,
      drawCoastline: true,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 0,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.01,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    expanded: {
      label: 'Expanded Line',
      hidden: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    group: {
      label: 'Group',
      hidden: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    svgDistort: {
      label: 'SVG Import',
      importedGroups: [],
      svgName: '',
      showOutlines: true,
      fillMode: 'hatch',
      fillDensity: 8,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillDotSize: 1.0,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillRadialCentralDensity: 1.0,
      fillRadialOuterDiameter: 1.0,
      fillAxes: 3,
      autoFit: true,
      scale: 1.0,
      offsetX: 0,
      offsetY: 0,
      noises: [],
      noiseTarget: 'all',
      seed: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
  };
  window.Vectura.SETTINGS = {
    uiTheme: 'dark',
    margin: 20,
    speedDown: 250,
    speedUp: 300,
    precision: 3,
    strokeWidth: 0.3,
    bgColor: '#121214',
    undoSteps: 20,
    truncate: true,
    cropExports: true,
    removeHiddenGeometry: true,
    outsideOpacity: 0.5,
    marginLineVisible: false,
    marginLineWeight: 0.2,
    marginLineColor: '#52525b',
    marginLineDotting: 0,
    showGuides: true,
    snapGuides: true,
    selectionOutline: true,
    selectionOutlineColor: '#ef4444',
    selectionOutlineWidth: 0.4,
    gridOverlay: false,
    gridOpacity: 0.2,
    gridStyle: 'cartesian',
    gridColor: '#ffffff',
    gridSize: 10,
    uiSections: {
      algorithm: false,
      algorithmTransform: true,
      algorithmConfiguration: false,
    },
    aboutVisible: true,
    touchModifiers: {
      shift: false,
      alt: false,
      meta: false,
      pan: false,
    },
    selectionMode: 'rect',
    documentUnits: 'metric',
    paperSize: 'letter',
    paperWidth: 216,
    paperHeight: 279,
    paperOrientation: 'landscape',
    showDocumentDimensions: false,
    optimizationScope: 'all',
    optimizationPreview: 'off',
    optimizationExport: true,
    optimizationOverlayColor: '#38bdf8',
    optimizationOverlayWidth: 0.2,
    activeTool: 'select',
    penMode: 'draw',
    scissorMode: 'line',
    cookiePreferencesEnabled: false,
    lightSource: null,
    optimizationDefaults: {
      bypassAll: false,
      steps: [
        { id: 'linesimplify', enabled: true, bypass: false, tolerance: 0.2, mode: 'curve' },
        { id: 'linesort', enabled: true, bypass: false, method: 'nearest', direction: 'vertical', grouping: 'combined' },
        { id: 'filter', enabled: false, bypass: false, minLength: 0, maxLength: 800, removeTiny: true },
        { id: 'multipass', enabled: false, bypass: false, passes: 2, offset: 0.2, jitter: 0, seed: 0 },
      ],
    },
    plotterOptimize: 0,
    paletteId: 'blues-01',
    autoColorization: {
      enabled: false,
      scope: 'all',
      mode: 'none',
      params: {
        penOffset: 0,
        penStride: 1,
        penMirror: false,
        penJitter: 0,
        radiusStart: 0,
        radiusEnd: 100,
        bandSize: 20,
        bandOffset: 0,
        bandGrowth: 0,
        bandStart: 0,
        bandEnd: 100,
        angleOffset: 0,
        angleSpan: 360,
        spiralTurns: 1,
        sizeCurve: 1,
        sizeInvert: false,
        randomSeed: 1,
      },
    },
    autoColorizationCollapsed: true,
    pensCollapsed: false,
    pens: [
      { id: 'pen-1', name: 'Pen 1', color: '#ffffff', width: 0.3 },
      { id: 'pen-2', name: 'Pen 2', color: '#dbeafe', width: 0.5 },
      { id: 'pen-3', name: 'Pen 3', color: '#93c5fd', width: 0.8 },
    ],
    globalLayerCount: 0,
  };
  window.Vectura.NOISE_IMAGES = window.Vectura.NOISE_IMAGES || {};
})();
