/**
 * Default algorithm parameters and mutable app settings.
 */
(() => {
  const Vectura = (window.Vectura = window.Vectura || {});
  const MM_PER_INCH = 25.4;
  const normalizeDocumentUnits = (value) => (`${value || ''}`.trim().toLowerCase() === 'imperial' ? 'imperial' : 'metric');
  const getDocumentUnitLabel = (units) => (normalizeDocumentUnits(units) === 'imperial' ? 'in' : 'mm');
  const mmToDocumentUnits = (value, units) => {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) return 0;
    return normalizeDocumentUnits(units) === 'imperial' ? numeric / MM_PER_INCH : numeric;
  };
  const documentUnitsToMm = (value, units) => {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) return 0;
    return normalizeDocumentUnits(units) === 'imperial' ? numeric * MM_PER_INCH : numeric;
  };
  const getDocumentUnitPrecision = (units, fallback = null) => {
    if (Number.isFinite(fallback)) return fallback;
    return normalizeDocumentUnits(units) === 'imperial' ? 2 : 1;
  };
  const getDocumentUnitStep = (units, fallback = null) => {
    if (Number.isFinite(fallback)) return fallback;
    return normalizeDocumentUnits(units) === 'imperial' ? 0.01 : 0.1;
  };
  const formatDocumentLength = (valueMm, units, options = {}) => {
    const {
      precision = null,
      includeUnit = true,
      trimTrailingZeros = false,
      spaceBeforeUnit = false,
    } = options;
    const resolvedUnits = normalizeDocumentUnits(units);
    const decimals = getDocumentUnitPrecision(resolvedUnits, precision);
    const displayValue = mmToDocumentUnits(valueMm, resolvedUnits);
    let text = Number(displayValue).toFixed(decimals);
    if (trimTrailingZeros && text.includes('.')) {
      text = text.replace(/\.?0+$/, '');
    }
    if (!includeUnit) return text;
    const unit = getDocumentUnitLabel(resolvedUnits);
    return `${text}${spaceBeforeUnit ? ' ' : ''}${unit}`;
  };
  window.Vectura.UnitUtils = {
    MM_PER_INCH,
    normalizeDocumentUnits,
    getDocumentUnitLabel,
    mmToDocumentUnits,
    documentUnitsToMm,
    getDocumentUnitPrecision,
    getDocumentUnitStep,
    formatDocumentLength,
  };
  // Shared manifest extras for the legacy "classic" skin family. Phase 0 carries the
  // dimensions through unchanged from the legacy CSS structure, so these defaults land as
  // no-ops visually but unlock the SkinManager pipeline (motion vars, swap-suppression).
  const CLASSIC_MANIFEST = {
    paneLeftWidth: 290,
    paneRightWidth: 258,
    bottomPaneHeight: 148,
    rowHeight: 30,
    motion: {
      sliderPulse: { dur: 550, ease: 'ease-out', peak: 0.36 },
      thumbRelease: { dur: 350, ease: 'ease-out' },
      btnFade: { dur: 300, ease: 'ease-out', dip: 0.42 },
      dialWave: { dur: 520, ease: 'cubic-bezier(0.23,1,0.32,1)', peak: 0.63, maxR: 24 },
      panelSlide: { dur: 220, ease: 'cubic-bezier(0.22,1,0.36,1)' },
      modalEnter: { dur: 220 },
      toastIn: { dur: 260 },
      toastOut: { dur: 200 },
    },
    capabilities: { dialReleaseWave: false, twoColControls: false },
  };
  const MERIDIAN_MANIFEST = Object.assign({}, CLASSIC_MANIFEST, {
    fontUi: "'Space Grotesk', system-ui, sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    capabilities: { dialReleaseWave: true, twoColControls: false },
  });
  window.Vectura.THEMES = {
    // Two families × three brightness slots: meridian (Modern) and classic.
    // App.toggleTheme cycles within the active family (dark → lark → light).
    // The Modern/Classic toggle in Document Setup hops to the same brightness
    // slot in the other family.
    dark: {
      id: 'dark',
      label: 'Dark',
      family: 'meridian',
      stylesheet: './src/ui/skin/meridian-dark.css',
      manifest: MERIDIAN_MANIFEST,
      colorScheme: 'dark',
      metaThemeColor: '#1b1b1b',
      documentBg: '#121214',
      pen1Color: '#e6f1ff',
      gridColor: '#ffffff',
      gridMinorColor: '#ffffff',
      // The renderer reads --render-canvas / --color-workspace via getComputedStyle.
      // Pushing them inline here guarantees they overwrite any stale values left by
      // a previously-active classic-* skin (which pushes its own dark workspace tokens).
      cssVars: {
        '--vectura-bg-rgb': '27 27 27',
        '--vectura-panel-rgb': '37 37 37',
        '--vectura-border-rgb': '54 54 54',
        '--vectura-text-rgb': '224 224 224',
        '--vectura-muted-rgb': '104 104 104',
        '--vectura-accent-rgb': '78 158 225',
        '--vectura-danger-rgb': '224 82 82',
        '--color-workspace': '#111111',
        '--ui-workspace': '#111111',
        '--render-canvas': '#121214',
      },
    },
    lark: {
      id: 'lark',
      label: 'Lark',
      family: 'meridian',
      stylesheet: './src/ui/skin/meridian-lark.css',
      manifest: MERIDIAN_MANIFEST,
      colorScheme: 'dark',
      metaThemeColor: '#1b1b1b',
      documentBg: '#ffffff',
      // Pure black ink for plotter realism on the white paper. Matches the
      // historical "lark" contract preserved in tests/integration/ui-bootstrap-panels.
      pen1Color: '#000000',
      gridColor: '#000000',
      gridMinorColor: '#000000',
      // Light canvas/paper paired with dark UI chrome. The full --color-* alias
      // set is pushed inline to maintain backward compatibility with legacy aliases (which have the same
      // specificity as [data-ui-skin] but load later) can't bleed through.
      cssVars: {
        '--vectura-bg-rgb': '27 27 27',
        '--vectura-panel-rgb': '37 37 37',
        '--vectura-border-rgb': '54 54 54',
        '--vectura-text-rgb': '224 224 224',
        '--vectura-muted-rgb': '104 104 104',
        '--vectura-accent-rgb': '78 158 225',
        '--vectura-danger-rgb': '224 82 82',
        '--color-bg': '#1b1b1b',
        '--color-panel': '#252525',
        '--color-border': '#363636',
        '--color-border-strong': '#484848',
        '--color-border-hover': '#484848',
        '--color-text': '#e0e0e0',
        '--color-text-soft': '#a8a8a8',
        '--color-muted': '#686868',
        '--color-formula-text': '#b0b0b0',
        '--color-accent': '#4e9ee1',
        '--color-surface': '#1e1e1e',
        '--color-surface-alt': '#1e1e1e',
        '--color-control': '#2c2c2c',
        '--color-control-hover': '#343434',
        '--color-read-surface': '#252525',
        '--color-touch-border': '#363636',
        '--color-mobile-handle-bg': 'rgba(27, 27, 27, 0.94)',
        '--color-workspace': '#d5d5d5',
        '--ui-workspace': '#d5d5d5',
        '--render-canvas': '#d5d5d5',
        // Medium-grey selection bounds + handle stroke so the dashed rect around
        // a selected object stays visible on the white artboard.
        '--render-selection-handle-stroke': '#9ca3af',
      },
    },
    light: {
      id: 'light',
      label: 'Light',
      family: 'meridian',
      stylesheet: './src/ui/skin/meridian-light.css',
      manifest: MERIDIAN_MANIFEST,
      colorScheme: 'light',
      metaThemeColor: '#efefef',
      documentBg: '#ffffff',
      pen1Color: '#0a1320',
      gridColor: '#000000',
      gridMinorColor: '#000000',
      // Full --color-* alias set pushed inline to maintain backward compatibility with legacy aliases
      // (which load after meridian-light.css and tie on specificity) don't bleed
      // through and dark-tint .tool-btn / .pendulum-card / etc.
      cssVars: {
        '--vectura-bg-rgb': '239 239 239',
        '--vectura-panel-rgb': '250 250 250',
        '--vectura-border-rgb': '200 200 200',
        '--vectura-text-rgb': '26 26 26',
        '--vectura-muted-rgb': '136 136 136',
        '--vectura-accent-rgb': '14 111 224',
        '--vectura-danger-rgb': '192 57 43',
        '--color-bg': '#efefef',
        '--color-panel': '#fafafa',
        '--color-border': '#c8c8c8',
        '--color-border-strong': '#a0a0a0',
        '--color-border-hover': '#a0a0a0',
        '--color-text': '#1a1a1a',
        '--color-text-soft': '#505050',
        '--color-muted': '#888888',
        '--color-formula-text': '#404040',
        '--color-accent': '#0e6fe0',
        '--color-surface': '#f2f2f2',
        '--color-surface-alt': '#f2f2f2',
        '--color-control': '#ffffff',
        '--color-control-hover': '#ebebeb',
        '--color-read-surface': '#fafafa',
        '--color-touch-border': '#c8c8c8',
        '--color-mobile-handle-bg': 'rgba(239, 239, 239, 0.96)',
        '--color-workspace': '#d5d5d5',
        '--ui-workspace': '#d5d5d5',
        '--render-canvas': '#d5d5d5',
        // Medium-grey selection bounds + handle stroke so the dashed rect around
        // a selected object stays visible on the white artboard.
        '--render-selection-handle-stroke': '#9ca3af',
      },
    },
    // Classic family — selected via Document Setup → Theme → Classic.
    'classic-dark': {
      id: 'classic-dark',
      label: 'Classic Dark',
      family: 'classic',
      stylesheet: './src/ui/skin/classic-dark.css',
      manifest: CLASSIC_MANIFEST,
      colorScheme: 'dark',
      metaThemeColor: '#09090b',
      documentBg: '#121214',
      pen1Color: '#ffffff',
      gridColor: '#ffffff',
      gridMinorColor: '#ffffff',
      cssVars: {
        '--vectura-bg-rgb': '9 9 11',
        '--vectura-panel-rgb': '24 24 27',
        '--vectura-border-rgb': '39 39 42',
        '--vectura-text-rgb': '228 228 231',
        '--vectura-muted-rgb': '113 113 122',
        '--vectura-accent-rgb': '250 250 250',
        '--vectura-danger-rgb': '239 68 68',
        '--color-bg': '#09090b',
        '--color-panel': '#18181b',
        '--color-border': '#27272a',
        '--color-border-strong': '#3f3f46',
        '--color-border-hover': '#52525b',
        '--color-text': '#e4e4e7',
        '--color-text-soft': '#a1a1aa',
        '--color-muted': '#71717a',
        '--color-formula-text': '#d4d4d8',
        '--color-accent': '#fafafa',
        '--color-surface': '#0f0f12',
        '--color-surface-alt': '#111113',
        '--color-control': '#141417',
        '--color-control-hover': '#1f1f23',
        '--color-read-surface': '#18181b',
        '--color-workspace': '#121214',
        '--color-touch-border': '#2f3036',
        '--color-mobile-handle-bg': 'rgba(9, 9, 11, 0.94)',
        '--shadow-panel': '0 12px 30px rgba(0, 0, 0, 0.4)',
        '--shadow-float': '0 10px 30px rgba(0, 0, 0, 0.35)',
        /* Render/designer/plotter values mirror classic-dark.css (zinc palette).
         * Updated 2026-05-20 (CSS-1 closure) — previously these inlined the
         * meridian-dark slate-blue tones (#0f172a, #67e8f9), which never matched
         * the rest of the classic-dark zinc chrome. */
        '--render-canvas': '#121214',
        '--render-shadow': 'rgba(0, 0, 0, 0.5)',
        '--render-paper-outline': '#3f3f46',
        '--render-frame-stroke': 'rgba(255,255,255,0.08)',
        '--render-guide-faint': 'rgba(244, 244, 245, 0.75)',
        '--render-selection-handle-fill': '#18181b',
        '--render-selection-handle-stroke': '#fafafa',
        '--render-cursor-stroke': 'white',
        '--render-marquee-stroke': 'rgba(161, 161, 170, 0.7)',
        '--render-marquee-fill': 'rgba(161, 161, 170, 0.12)',
        '--render-direct-stroke': '#22d3ee',
        '--render-direct-handle-line': 'rgba(34, 211, 238, 0.65)',
        '--render-direct-handle-fill': '#0f0f12',
        '--render-underlay-fill': 'rgba(9, 9, 11, 0.92)',
        '--render-underlay-stroke': 'rgba(9, 9, 11, 1)',
        '--designer-grid-bg': '#0f0f12',
        '--designer-grid-line': 'rgba(161,161,170,0.14)',
        '--designer-fill-active': 'rgba(212, 212, 216, 0.10)',
        '--designer-fill-inactive': 'rgba(212, 212, 216, 0.05)',
        '--designer-stroke-active': '#e4e4e7',
        '--designer-stroke-inactive': 'rgba(228, 228, 231, 0.55)',
        '--designer-shading-stroke': 'rgba(212, 212, 216, 0.6)',
        '--designer-control-line': 'rgba(228, 228, 231, 0.55)',
        '--designer-control-fill': '#0f0f12',
        '--designer-control-anchor': '#fafafa',
        '--designer-control-handle': '#e4e4e7',
        '--plotter-bg': '#0f0f12',
        '--plotter-path-base': 'rgba(113,113,122,0.35)',
        '--plotter-head': '#fafafa',
      },
    },
    'classic-lark': {
      id: 'classic-lark',
      label: 'Classic Lark',
      family: 'classic',
      stylesheet: './src/ui/skin/classic-lark.css',
      manifest: CLASSIC_MANIFEST,
      colorScheme: 'dark',
      metaThemeColor: '#09090b',
      documentBg: '#ffffff',
      pen1Color: '#000000',
      gridColor: '#000000',
      gridMinorColor: '#000000',
      cssVars: {
        '--vectura-bg-rgb': '9 9 11',
        '--vectura-panel-rgb': '24 24 27',
        '--vectura-border-rgb': '39 39 42',
        '--vectura-text-rgb': '228 228 231',
        '--vectura-muted-rgb': '113 113 122',
        '--vectura-accent-rgb': '250 250 250',
        '--vectura-danger-rgb': '239 68 68',
        '--color-bg': '#09090b',
        '--color-panel': '#18181b',
        '--color-border': '#27272a',
        '--color-border-strong': '#3f3f46',
        '--color-border-hover': '#52525b',
        '--color-text': '#e4e4e7',
        '--color-text-soft': '#a1a1aa',
        '--color-muted': '#71717a',
        '--color-formula-text': '#d4d4d8',
        '--color-accent': '#fafafa',
        '--color-surface': '#0f0f12',
        '--color-surface-alt': '#111113',
        '--color-control': '#141417',
        '--color-control-hover': '#1f1f23',
        '--color-read-surface': '#18181b',
        '--color-workspace': '#121214',
        '--color-touch-border': '#2f3036',
        '--color-mobile-handle-bg': 'rgba(9, 9, 11, 0.94)',
        '--shadow-panel': '0 12px 30px rgba(0, 0, 0, 0.4)',
        '--shadow-float': '0 10px 30px rgba(0, 0, 0, 0.35)',
        '--render-canvas': '#dadde3',
        '--render-shadow': 'rgba(15, 23, 42, 0.18)',
        '--render-paper-outline': '#a1a1aa',
        '--render-frame-stroke': 'rgba(24,24,27,0.12)',
        '--render-guide-faint': 'rgba(24, 24, 27, 0.45)',
        '--render-selection-handle-fill': '#ffffff',
        '--render-selection-handle-stroke': '#18181b',
        '--render-cursor-stroke': '#18181b',
        '--render-marquee-stroke': 'rgba(71, 85, 105, 0.55)',
        '--render-marquee-fill': 'rgba(71, 85, 105, 0.10)',
        '--render-direct-stroke': '#0284c7',
        '--render-direct-handle-line': 'rgba(14, 165, 233, 0.55)',
        '--render-direct-handle-fill': '#ffffff',
        '--render-underlay-fill': 'rgba(255, 255, 255, 0.95)',
        '--render-underlay-stroke': 'rgba(255, 255, 255, 1)',
        /* Designer overlays the dark chrome (not the light canvas) so we keep
         * the dark-grid zinc tones from classic-lark.css. Updated 2026-05-20
         * (CSS-1 closure) — previously inlined meridian's slate-blue values. */
        '--designer-grid-bg': '#0f0f12',
        '--designer-grid-line': 'rgba(161,161,170,0.14)',
        '--designer-fill-active': 'rgba(212, 212, 216, 0.10)',
        '--designer-fill-inactive': 'rgba(212, 212, 216, 0.05)',
        '--designer-stroke-active': '#e4e4e7',
        '--designer-stroke-inactive': 'rgba(228, 228, 231, 0.55)',
        '--designer-shading-stroke': 'rgba(212, 212, 216, 0.6)',
        '--designer-control-line': 'rgba(228, 228, 231, 0.55)',
        '--designer-control-fill': '#0f0f12',
        '--designer-control-anchor': '#fafafa',
        '--designer-control-handle': '#e4e4e7',
        '--plotter-bg': '#f4f5f8',
        '--plotter-path-base': 'rgba(82,82,91,0.35)',
        '--plotter-head': '#18181b',
      },
    },
    'classic-light': {
      id: 'classic-light',
      label: 'Classic Light',
      family: 'classic',
      stylesheet: './src/ui/skin/classic-light.css',
      manifest: CLASSIC_MANIFEST,
      colorScheme: 'light',
      metaThemeColor: '#f5f5f5',
      documentBg: '#ffffff',
      pen1Color: '#000000',
      gridColor: '#000000',
      gridMinorColor: '#000000',
      cssVars: {
        '--vectura-bg-rgb': '243 244 246',
        '--vectura-panel-rgb': '229 231 235',
        '--vectura-border-rgb': '212 212 216',
        '--vectura-text-rgb': '24 24 27',
        '--vectura-muted-rgb': '82 82 91',
        '--vectura-accent-rgb': '9 9 11',
        '--vectura-danger-rgb': '220 38 38',
        '--color-bg': '#f3f4f6',
        '--color-panel': '#e5e7eb',
        '--color-border': '#d4d4d8',
        '--color-border-strong': '#a1a1aa',
        '--color-border-hover': '#71717a',
        '--color-text': '#18181b',
        '--color-text-soft': '#3f3f46',
        '--color-muted': '#52525b',
        '--color-formula-text': '#52525b',
        '--color-accent': '#09090b',
        '--color-surface': '#f4f5f8',
        '--color-surface-alt': '#eceef2',
        '--color-control': '#ffffff',
        '--color-control-hover': '#f8fafc',
        '--color-read-surface': '#f8fafc',
        '--color-workspace': '#dadde3',
        '--color-touch-border': '#cbd5e1',
        '--color-mobile-handle-bg': 'rgba(243, 244, 246, 0.96)',
        '--shadow-panel': '0 12px 30px rgba(15, 23, 42, 0.14)',
        '--shadow-float': '0 10px 30px rgba(15, 23, 42, 0.16)',
        '--render-canvas': '#dadde3',
        '--render-shadow': 'rgba(15, 23, 42, 0.18)',
        '--render-paper-outline': '#a1a1aa',
        '--render-frame-stroke': 'rgba(24,24,27,0.12)',
        '--render-guide-faint': 'rgba(24, 24, 27, 0.45)',
        '--render-selection-handle-fill': '#ffffff',
        '--render-selection-handle-stroke': '#18181b',
        '--render-cursor-stroke': '#18181b',
        /* Marquee + designer-grid tinted with zinc-700 (63,63,70) to align with
         * the classic-light --ui-text-2 readout color — matches classic-light.css
         * after the 2026-05-20 CSS-1 closure. */
        '--render-marquee-stroke': 'rgba(63, 63, 70, 0.55)',
        '--render-marquee-fill': 'rgba(63, 63, 70, 0.10)',
        '--render-direct-stroke': '#0284c7',
        '--render-direct-handle-line': 'rgba(2, 132, 199, 0.55)',
        '--render-direct-handle-fill': '#ffffff',
        '--render-underlay-fill': 'rgba(255, 255, 255, 0.95)',
        '--render-underlay-stroke': 'rgba(255, 255, 255, 1)',
        '--designer-grid-bg': '#f4f5f8',
        '--designer-grid-line': 'rgba(63,63,70,0.14)',
        '--designer-fill-active': 'rgba(2, 132, 199, 0.12)',
        '--designer-fill-inactive': 'rgba(2, 132, 199, 0.05)',
        '--designer-stroke-active': '#0284c7',
        '--designer-stroke-inactive': 'rgba(2, 132, 199, 0.50)',
        '--designer-shading-stroke': 'rgba(14, 165, 233, 0.55)',
        '--designer-control-line': 'rgba(2, 132, 199, 0.45)',
        '--designer-control-fill': '#ffffff',
        '--designer-control-anchor': '#0284c7',
        '--designer-control-handle': '#38bdf8',
        '--plotter-bg': '#f4f5f8',
        '--plotter-path-base': 'rgba(82,82,91,0.35)',
        '--plotter-head': '#09090b',
      },
    },
  };
  window.Vectura.ALGO_DEFAULTS = {
    wavetable: {
      preset: 'wavetable-rolling-hills',
      lineStructure: 'horizontal',
      lines: 130,
      noiseType: 'simplex',
      noiseImageId: '',
      noiseImageName: '',
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 9,
          zoom: 0.02,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          polygonZoomReference: 0.02,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      imageAlgo: 'luma',
      imageThreshold: 0.5,
      imagePosterize: 5,
      imageBlur: 0,
      amplitude: 9,
      zoom: 0.02,
      tilt: 0,
      gap: 1.0,
      freq: 1.0,
      lineOffset: 180,
      continuity: 'none',
      dampenExtremes: false,
      overlapPadding: 0,
      flatCaps: false,
      edgeFadeMode: 'both',
      edgeFade: 0,
      edgeFadeThreshold: 0,
      edgeFadeFeather: 0,
      noiseAngle: 0,
      verticalFade: 0,
      verticalFadeThreshold: 0,
      verticalFadeFeather: 0,
      verticalFadeMode: 'both',
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    rings: {
      label: 'Rings',
      preset: 'rings-default',
      rings: 15,
      centerDiameter: 0,
      outerDiameter: 140,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 10,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          applyMode: 'topdown',
          ringDrift: 0.5,
          ringRadius: 100,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.001,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      amplitude: 10,
      noiseScale: 0.01,
      noiseOffsetX: 0,
      noiseOffsetY: 0,
      noiseLayer: 0.5,
      noiseRadius: 100,
      gap: 1.2,
      gapCurveStart: 1,
      gapCurveEnd: 1,
      spacingVariance: 0,
      barkRings: 5,
      barkGap: 0.5,
      breakCount: 0,
      breakRadiusMin: 0,
      breakRadiusMax: 100,
      breakLengthVariance: 0,
      breakNoiseSeed: 0,
      breakWidthMin: 2,
      breakWidthMax: 6,
      breakWidthVariance: 0,
      centerDrift: 0,
      biasStrength: 0,
      biasAngle: 0,
      rayCount: 0,
      rayLength: 2.5,
      rayMinLength: 0.5,
      rayMaxLength: 2.5,
      rayInnerFraction: 0.15,
      raySeed: 0,
      rayLengthVariance: 0,
      knotCount: 0,
      knotMinSize: 1,
      knotMaxSize: 5,
      knotSeed: 0,
      knotIntensity: 0.6,
      knotSpread: 30,
      knotStrengthVariance: 0,
      knotDirection: 'outer',
      knotSize: 5,
      knotSizeVariance: 0,
      vMarkCount: 0,
      vMarkDepth: 5,
      vMarkSpread: 1,
      vMarkSize: 50,
      vMarkSeed: 0,
      scarCount: 0,
      scarDepth: 3,
      scarWidth: 5,
      scarSize: 8,
      scarSeed: 0,
      thickRingCount: 0,
      thickRingDensity: 0.85,
      thickRingWidth: 3,
      thickRingSeed: 0,
      crackCount: 0,
      crackDepth: 0.5,
      crackSpread: 4,
      crackNoise: 0.3,
      crackSeed: 0,
      crackOutline: false,
      barkType: 'smooth',
      barkRoughness: 4,
      barkRoughnessConfinement: 0.5,
      barkFreq: 3,
      barkFurrowCount: 14,
      barkFurrowDepth: 5,
      barkFurrowWidth: 0.12,
      barkPlateCount: 10,
      barkPlateRelief: 3.5,
      barkPlateVariance: 0.4,
      barkPaperStrips: 7,
      barkPaperPeel: 2.5,
      barkPaperJitter: 0.3,
      barkFiberCount: 28,
      barkFiberAmplitude: 2.5,
      barkFiberPhaseShift: 0.25,
      barkScaleColumns: 18,
      barkScaleRelief: 3,
      barkScaleTaper: 0.6,
      barkCrackDensity: 8,
      barkCrackDepth: 5,
      barkCrackWidth: 0.07,
      barkLenticleCount: 18,
      barkLenticleDepth: 3,
      barkLenticleWidth: 0.12,
      barkWeaveFreq: 9,
      barkWeaveAmplitude: 2,
      barkWeaveAngle: 45,
      offsetX: 0,
      offsetY: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    topo: {
      label: 'Topo',
      preset: 'topo-mountain-range',
      resolution: 120,
      levels: 30,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.003,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 3,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.003,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      noiseScale: 0.003,
      noiseOffsetX: 0,
      noiseOffsetY: 0,
      octaves: 3,
      lacunarity: 2.0,
      gain: 0.5,
      sensitivity: 1.0,
      thresholdOffset: 0,
      mappingMode: 'marching',
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    petalisDesigner: {
      label: 'Petalis',
      preset: 'petalisdesigner-default',
      petalProfile: 'teardrop',
      petalScale: 34,
      petalWidthRatio: 0.74,
      petalSizeRatio: 1,
      leafSideWidth: 1,
      leafBaseHandle: 0.35,
      leafSideHandle: 0.4,
      leafTipHandle: 0.35,
      designerOuter: null,
      designerInner: null,
      petalSteps: 32,
      layering: true,
      anchorToCenter: 'central',
      anchorRadiusRatio: 1,
      tipSharpness: 1,
      tipTwist: 0,
      tipCurl: 0,
      baseFlare: 0,
      basePinch: 0,
      radiusScale: 0.2,
      radiusScaleCurve: 1.2,
      sizeJitter: 0,
      rotationJitter: 0,
      count: 40,
      countJitter: 0,
      bloom: 100,
      petalAsymmetry: 0,
      petalCupping: 0,
      innerCount: 0,
      outerCount: 6,
      ringSplit: 0.45,
      innerOuterLock: false,
      designerSymmetry: 'none',
      designerInnerSymmetry: 'none',
      designerOuterSymmetry: 'none',
      petalVisualizerViewStyle: 'overlay',
      profileTransitionPosition: 50,
      profileTransitionFeather: 0,
      ringOffset: 12,
      spiralMode: 'golden',
      customAngle: 137.5,
      spiralTightness: 1.1,
      radialGrowth: 0.05,
      spiralStart: 0,
      spiralEnd: 1,
      angularDrift: 0,
      driftStrength: 0.1,
      driftNoise: 0.2,
      driftNoises: [],
      centerSizeMorph: 0,
      centerSizeCurve: 1.2,
      centerShapeMorph: 0.2,
      centerProfile: 'oval',
      centerCurlBoost: 0,
      budMode: false,
      budRadius: 0.15,
      budTightness: 0.5,
      centerType: 'disk',
      centerRadius: 8,
      centerDensity: 20,
      centerFalloff: 0.6,
      centerFilamentNoises: [],
      centerRing: false,
      centerRingRadius: 14,
      centerRingDensity: 16,
      centerConnectors: false,
      connectorCount: 60,
      connectorLength: 10,
      connectorJitter: 0.3,
      shadings: [],
      useDesignerShapeOnly: true,
      petalModifiers: [],
      centerModifiers: [
        {
          id: 'mod-1',
          enabled: false,
          type: 'ripple',
          amount: 2,
          frequency: 6,
          scale: 0.2,
          noises: [],
          offsetX: 0,
          offsetY: 0,
          radius: 10,
          seed: 0,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    rainfall: {
      label: 'Rainfall',
      preset: 'rainfall-default',
      count: 210,
      traceLength: 120,
      traceStep: 3,
      turbulence: 0.25,
      lengthJitter: 0,
      stepJitter: 0,
      gustStrength: 0,
      rainfallAngle: 150,
      angleJitter: 0,
      windAngle: 180,
      windStrength: 0,
      dropSize: 3,
      dropSizeJitter: 0,
      dropRotate: 0,
      dropShape: 'none',
      dropFill: 'none',
      fillDensity: 1,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillDotSize: 1.0,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillAxes: 3,
      widthMultiplier: 1,
      thickeningMode: 'parallel',
      trailBreaks: 'drop',
      breakSpacing: 10,
      breakLengthJitter: 0,
      breakWidthJitter: 0,
      breakRandomness: 0,
      silhouetteId: '',
      silhouetteName: '',
      silhouetteWidth: 200,
      silhouetteHeight: 200,
      silhouetteTilesX: 1,
      silhouetteTilesY: 1,
      silhouetteSpacing: 0,
      silhouetteOffsetX: 0,
      silhouetteOffsetY: 0,
      silhouetteInvert: false,
      noiseApply: 'trails',
      noises: [],
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    flowfield: {
      preset: 'flowfield-default',
      flowMode: 'angle',
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 2,
          lacunarity: 2.0,
          gain: 0.5,
          fieldMode: 'angle',
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.01,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseType: 'simplex',
      noiseScale: 0.01,
      lacunarity: 2.0,
      gain: 0.5,
      density: 1200,
      stepLen: 5,
      maxSteps: 200,
      force: 1.0,
      angleOffset: 0,
      chaos: 0.1,
      octaves: 2,
      minSteps: 2,
      minLength: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    lissajous: {
      preset: 'lissajous-default',
      freqX: 3,
      freqY: 2,
      damping: 0.001,
      phase: 1.5,
      resolution: 200,
      scale: 0.8,
      truncateStart: 0,
      truncateEnd: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
      closeLines: false,
    },
    pattern: {
      label: 'Pattern',
      patternFilter: 'lines',
      patternId: window.Vectura?.PATTERNS?.[0]?.id || '',
      scale: 1,
      originX: 0,
      originY: 0,
      tileSpacingX: 0,
      tileSpacingY: 0,
      tileMethod: 'grid',
      penMapping: {},
      removeSeams: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
      tileEdgeCurves: false,
      patternFills: [],
      fillSensitivity: 2.0,
      patternCustomPaths: [],
    },
    harmonograph: {
      label: 'Harmonograph',
      preset: 'harmonograph-default',
      machineType: 'lateral',
      renderMode: 'line',
      samples: 6000,
      duration: 30,
      scale: 0.35,
      paperRotation: 0,
      dashLength: 4,
      dashGap: 2,
      pointStride: 4,
      pointSize: 0.4,
      segmentStride: 6,
      segmentLength: 6,
      gapSize: 0,
      gapOffset: 0,
      gapRandomness: 0,
      widthMultiplier: 1,
      thickeningMode: 'parallel',
      loopDrift: 0,
      settleThreshold: 0,
      settleWindow: 24,
      plotStart: 0,
      plotEnd: 100,
      pendulumParamLocks: {},
      showPendulumGuides: false,
      pendulumGuideColor: '#f59e0b',
      pendulumGuideWidth: 0.25,
      pendulums: [
        {
          id: 'pend-1',
          enabled: true,
          ampX: 100,
          ampY: 100,
          phaseX: 90,
          phaseY: 0,
          damp: 0.002,
          freq: 3,
          micro: 0.01,
        },
        {
          id: 'pend-2',
          enabled: true,
          ampX: 100,
          ampY: 100,
          phaseX: 0,
          phaseY: 90,
          damp: 0.002,
          freq: 2,
          micro: 0.02,
        },
        {
          id: 'pend-3',
          enabled: true,
          ampX: 50,
          ampY: -50,
          phaseX: 270,
          phaseY: 0,
          damp: 0.002,
          freq: 3,
          micro: -0.01,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    pendula: {
      label: 'Pendula',
      preset: 'pendula-default',
      machineType: 'lateral',
      renderMode: 'line',
      samples: 6000,
      duration: 30,
      scale: 0.35,
      paperRotation: 0,
      dashLength: 4,
      dashGap: 2,
      pointStride: 4,
      pointSize: 0.4,
      segmentStride: 6,
      segmentLength: 6,
      gapSize: 0,
      gapOffset: 0,
      gapRandomness: 0,
      widthMultiplier: 1,
      thickeningMode: 'parallel',
      loopDrift: 0,
      settleThreshold: 0,
      settleWindow: 24,
      plotStart: 0,
      plotEnd: 100,
      pendulumParamLocks: {},
      showPendulumGuides: false,
      pendulumGuideColor: '#f59e0b',
      pendulumGuideWidth: 0.25,
      pendulums: [
        { id: 'pend-1', enabled: true, ampX: 100, ampY: 100, phaseX: 90, phaseY: 0, damp: 0.0008, freq: 2, micro: 0 },
        { id: 'pend-2', enabled: true, ampX: 40, ampY: 40, phaseX: 0, phaseY: 90, damp: 0.0008, freq: 3, micro: 0 },
      ],
      motion: { sources: [], edges: [] },
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    spiral: {
      preset: 'spiral-default',
      loops: 10,
      res: 100,
      noiseAmp: 10,
      noiseFreq: 0.1,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'turbulence',
          blend: 'add',
          amplitude: 10,
          zoom: 0.1,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          applyMode: 'topdown',
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          polygonZoomReference: 0.1,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      startR: 5,
      angleOffset: 0,
      pulseAmp: 0,
      pulseFreq: 2,
      axisSnap: true,
      close: false,
      closeFeather: 0.5,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    halftone: {
      label: 'Dotscreen',
      is3d: false,
      category: 'Image',
      preset: 'halftone-default',
      imageSourceKind: 'builtin',
      imageSrc: '',
      imageId: '',
      imageName: '',
      dotSpacing: 4.8,
      maxDotSize: 4.6,
      minDotSize: 0,
      dotThreshold: 4,
      gridAngle: 0,
      dotGrid: 'square',
      dotShape: 'circle',
      dotSides: 6,
      dotPoints: 5,
      dotPetals: 5,
      dotTeeth: 8,
      dotAspect: 1,
      dotJitter: 0,
      dotSpin: 0,
      dotSpinAmount: 0,
      dotSpinCurve: 'linear',
      dotSpinDir: 0,
      smartEdges: false,
      maxDots: 14000,
      brightness: 0,
      contrast: 8,
      gamma: 1,
      invert: false,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    imageWeave: {
      label: 'Weave',
      is3d: false,
      category: 'Image',
      preset: 'imageweave-default',
      imageSourceKind: 'builtin',
      imageSrc: '',
      imageId: '',
      imageName: '',
      lineCount: 160,
      lineAngle: 0,
      amplitude: 1.4,
      frequency: 5000,
      detail: 72,
      continuity: 'none',
      connectEnds: false,
      drawWhiteAreas: true,
      brightness: 0,
      contrast: 0,
      blackPoint: 0,
      whitePoint: 100,
      invert: false,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    text: {
      label: 'Text',
      hidden: true,
      is3d: false,
      category: 'Typography',
      preset: 'text-default',
      text: 'Vectura',
      font: 'google:inter',
      // Type-layout mode (Illustrator-style). 'point' = classic auto-sized box
      // (default; all historical layers/files behave as before). 'area' = a fixed
      // frame the text word-wraps inside; frameWidth/frameHeight (mm, local space)
      // define the frame and only carry meaning in area mode.
      textMode: 'point',
      frameWidth: 0,
      frameHeight: 0,
      fontSize: 40,
      tracking: 0,
      lineHeight: 1.4,
      align: 'center',
      fitToFrame: true,
      fillRatio: 0.9,
      offsetX: 0,
      offsetY: 0,
      jitter: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
      // Outline rendering: native glyph beziers (web faces only) + plot order.
      bezierOutline: true,
      plotOrder: 'leftToRight',
      // Merge Overlaps welds kerned/overlapping glyph contours (RA, AV, connected
      // scripts) into clean non-crossing outlines. On by default; it welds ONLY the
      // glyphs whose ink genuinely overlaps, so every non-touching glyph keeps its
      // native bezier outline — merge and full curve accuracy coexist by default.
      mergeOverlaps: true,
      // Stroke emphasis — heavier outlines via parallel offset passes (shared
      // GeometryUtils.thickenPaths engine, also used by Harmonograph/Rainfall).
      outlineStroke: true,
      outlineThickness: 1,
      thickeningMode: 'parallel',
      // Banded bold (built-in face): concentric pass spacing = penW·(1−inkOverlap)
      // so adjacent pen passes overlap by this fraction of the pen width — gapless
      // ink without doubled strokes. Percent, 0–60.
      inkOverlap: 15,
      // Pattern fill of glyph interiors (web outline faces only) — reuses the
      // shared fill engine; every fill type/parameter mirrors the paint bucket.
      fillEnabled: false,
      fillType: 'hatch',
      fillDensity: 21,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillWaveSmoothing: 1.0,
      fillWaveFrequency: 1.0,
      fillDotLength: 0,
      fillDotRotation: 0,
      fillDotSize: 0.6,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillDotShape: 'circle',
      fillDotJitter: 0,
      fillLineCount: 1,
      fillAxes: 3,
      fillPolyTile: 'grid',
      fillPolyPadding: 0,
      fillPolyRotation: 0,
      fillPolyRotationStep: 0,
      fillPolyScaleStep: 0,
      fillPolyScale: 1,
      fillSpiralTightness: 0.5,
      fillSpiralDirection: 'cw',
      fillRadialSkip: 0,
      fillContourDirection: 'inset',
      fillContourStepVariance: 0,
      fillContourSimplify: 0.05,
      fillContourCenterPadding: 0,
      fillContourBezier: true,
      fillContourSmoothing: 0.6,
      fillFlowFieldType: 'perlin',
      fillFlowNoiseScale: 6.0,
      fillFlowSeed: 1,
      fillFlowTraceLen: 60,
      fillFlowSeparation: 2.5,
      fillVoronoiSeeds: 60,
      fillVoronoiJitter: 0.5,
      fillVoronoiStroke: 'boundary',
      fillVoronoiSeedMode: 'random',
      fillTruchetTileSet: 'quarter-arcs',
      fillTruchetTileSize: 6,
      fillTruchetSeed: 1,
      fillTruchetRotations: 4,
      fillMazeCellSize: 5,
      fillMazeAlgorithm: 'dfs',
      fillMazeBranchBias: 0.5,
      fillMazeSeed: 1,
      fillMazeWallMode: 'walls',
      fillScribbleSmoothness: 0.6,
      fillScribbleSeed: 1,
      fillScribbleCoverage: 1.0,
      fillLsysPreset: 'coral',
      fillLsysIterations: 4,
      fillLsysAngleVariance: 8,
      fillLsysSeed: 1,
      fillLsysScale: 1.0,
      fillHalftoneSource: 'radial',
      fillHalftoneMinR: 0.2,
      fillHalftoneMaxR: 1.5,
      fillHalftoneFrequency: 5,
      fillHalftoneAngle: 0,
      fillHalftoneInvert: 'off',
      fillStripeBandWidth: 4,
      fillStripeGap: 2,
      fillStripeAngle: 0,
      fillStripePrimary: 'hatch',
      fillStripeSecondary: 'none',
      fillStripeSecondaryDensity: 2,
      fillSpiroRatioA: 5,
      fillSpiroRatioB: 3,
      fillSpiroPhase: 0,
      fillSpiroTurns: 50,
      fillSpiroDeformation: 0,
      fillWeavePattern: 'plain',
      fillWeaveStrandWidth: 1.5,
      fillWeaveGap: 0.3,
      fillWeaveAngle: 0,
      fillWeaveOver: 1,
      fillWeaveUnder: 1,
      // ── Synthesis-panel typography ───────────────────────────────
      // Weight of the active face. Web faces map Regular/Medium/Semibold/Bold
      // → 400/500/600/800; built-in single-stroke faces ignore weight.
      fontWeight: 'Regular',
      // Affine glyph scaling as a percentage of natural size (100 = unscaled).
      vScale: 100,
      hScale: 100,
      // Per-PAIR manual kern: a sparse map keyed by caret index (the gap between
      // char c-1 and char c) → extra advance for that single gap, in font-relative
      // units (built-in) / mm (web), matching `tracking`'s per-face units. Only
      // editable from text-edit mode with the caret between two letters; there is
      // no global uniform kern (that role belongs to `tracking`).
      kernPairs: {},
      // Vertical baseline shift in mm (positive raises the whole block).
      baselineShift: 0,
      // Per-character rotation in degrees (deterministic; seeded like jitter).
      charRotation: 0,
      // Case / position transforms. Applied via the face's OpenType feature
      // when present, otherwise synthesized (scale + reposition).
      allCaps: false,
      smallCaps: false,
      superscript: false,
      subscript: false,
      underline: false,
      strikethrough: false,
      // ── Underline / strikethrough decoration ─────────────────────
      // Strikethrough sits at the typeface's optical midpoint (x-height
      // centre) by default; the offset nudges it (mm, positive raises).
      // It shares the same pen weight, thickening mechanism, and line
      // style controls as the underline.
      strikethroughOffset: 0,
      strikethroughThickness: 1,
      // parallel | sinusoidal | snake | hatch | cross
      strikethroughThickenMode: 'parallel',
      // solid | dashed | dotted | dash-dot | long-dash | dense-dot
      strikethroughStyle: 'solid',
      // Underline position offset (mm, positive lowers the rule), pen
      // weight, thickening mechanism, line style, and descender tail
      // breaks (gap, mm, centred on each glyph's below-underline ink).
      underlineOffset: 0,
      underlineThickness: 1,
      underlineThickenMode: 'parallel', // parallel | sinusoidal | snake | hatch | cross
      underlineStyle: 'solid', // solid | dashed | dotted | dash-dot | long-dash | dense-dot
      underlineBreak: false,
      underlineBreakGap: 1.5,
      // ── Synthesis-panel paragraph ────────────────────────────────
      // Indents + paragraph spacing in mm; hyphenation aids frame-fit wraps.
      indentLeft: 0,
      indentRight: 0,
      indentFirst: 0,
      spaceBefore: 0,
      spaceAfter: 0,
      hyphenate: false,
      // OpenType features — honoured when the web face's GSUB/GPOS tables
      // expose them; silently ignored on faces (or built-ins) that don't.
      otLigatures: true,
      otContextual: false,
      otDiscretionary: false,
      otSwash: false,
      otStylistic: false,
      otFractions: false,
      otFigures: 'default', // default | tabular | oldstyle
      otPosition: 'default', // default | super | sub
      // ── Synthesis-panel fill placement ───────────────────────────
      // Inset erodes the fill region inward from the glyph edge (mm); offset
      // translates the fill window across the glyph as a fraction of the glyph
      // block extent (-1..1) while the outline stays put.
      fillInsetEnabled: false,
      fillInset: 1.5,
      fillOffsetX: 0,
      fillOffsetY: 0,
      // Radius (mm) the fill-offset pad edge maps to — user-set via the vertical
      // slider beside the XY pad (1–1000mm). Both X and Y clamp to this bound.
      fillOffsetMax: 20,
      // Radial-fill centerpoint offset (mm) from the fill region's bounds centre,
      // driven by the Centerpoint XY pad shown only for the radial fill type. Fed
      // to the pattern engine as shiftX/shiftY (see pattern.js radialFill). Max is
      // the pad-edge radius, mirroring fillOffsetMax.
      fillShiftX: 0,
      fillShiftY: 0,
      fillShiftMax: 20,
    },
    grid: {
      preset: 'grid-default',
      rows: 20,
      cols: 20,
      distortion: 10,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.05,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 1,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.05,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseScale: 0.05,
      type: 'warp',
      chaos: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    phylla: {
      preset: 'phylla-sunflower',
      count: 500,
      spacing: 5,
      angleStr: 137.5,
      divergence: 1.0,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 1,
          zoom: 0.05,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          octaves: 1,
          lacunarity: 2.0,
          gain: 0.5,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [],
          polygonZoomReference: 0.05,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      noiseInf: 0,
      dotSize: 1.0,
      shapeType: 'circle',
      sides: 6,
      sideJitter: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    boids: {
      preset: 'boids-default',
      count: 100,
      steps: 100,
      speed: 2,
      sepDist: 10,
      alignDist: 20,
      cohDist: 20,
      force: 0.05,
      sepWeight: 1.2,
      alignWeight: 1.0,
      cohWeight: 0.9,
      mode: 'birds',
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    attractor: {
      preset: 'attractor-default',
      type: 'lorenz',
      iter: 1200,
      scale: 3,
      sigma: 10,
      rho: 28,
      beta: 2.66,
      dt: 0.01,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    hyphae: {
      preset: 'hyphae-default',
      sources: 2,
      steps: 50,
      branchProb: 0.05,
      angleVar: 0.5,
      segLen: 3,
      maxBranches: 1000,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    shapePack: {
      label: 'Shape Pack',
      preset: 'shapepack-default',
      shape: 'circle',
      count: 500,
      minR: 2,
      maxR: 20,
      padding: 1,
      attempts: 200,
      segments: 32,
      rotationStep: 0,
      perspectiveType: 'none',
      perspective: 0,
      perspectiveX: 0,
      perspectiveY: 0,
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    terrain: {
      label: 'Terrain',
      is3d: true,
      preset: 'terrain-default',
      perspectiveMode: 'one-point',
      horizonHeight: 50,
      vanishingPointX: 50,
      vpLeftX: 20,
      vpRightX: 80,
      isoAngle: 30,
      depthCompression: 60,
      depthScale: 80,
      depthSlices: 80,
      xResolution: 240,
      occlusion: true,
      mountainAmplitude: 40,
      mountainFrequency: 0.008,
      mountainOctaves: 5,
      mountainLacunarity: 2.0,
      mountainGain: 0.5,
      peakSharpness: 2.0,
      valleyCount: 2,
      valleyDepth: 30,
      valleyWidth: 20,
      valleyShape: 0.4,
      valleyMeander: 40,
      riversEnabled: false,
      riverCount: 2,
      riverWidth: 3,
      riverDepth: 8,
      riverMeander: 50,
      oceansEnabled: false,
      waterLevel: 20,
      drawCoastline: true,
      // Free 3D view (consumed only when perspectiveMode === 'free-3d'): routes
      // the heightfield through the shared Geometry3D engine for yaw/pitch/roll
      // orbit + the cross-cutting shading powers. Neutral/off by default so the
      // legacy perspective modes are entirely unaffected.
      yaw: -25,
      pitch: 58,
      roll: 0,
      projection: 'orthographic',
      cameraDistance: 620,
      focalLength: 520,
      // Footprint fan: 1 = the native rectangle; >1 widens the FAR (top) edge up
      // to 10× the near (base) edge, turning the rectangle into a trapezoid that
      // opens away from the viewer. 1 by default → shape unchanged.
      topWidth: 1,
      depthCue: 'off',
      depthCueStrength: 60,
      emphasizeOutline: false,
      outlineWeight: 2,
      showCreases: false,
      creaseAngle: 35,
      hiddenLineMode: 'remove',
      depthBias: 0.5,
      hatchEnable: false,
      lightAzimuth: 135,
      lightElevation: 45,
      hatchAngle: 45,
      hatchSpacing: 6,
      crossHatch: false,
      noises: [
        {
          id: 'noise-1',
          enabled: true,
          type: 'simplex',
          blend: 'add',
          amplitude: 0,
          zoom: 0.01,
          freq: 1.0,
          angle: 0,
          shiftX: 0,
          shiftY: 0,
          tileMode: 'off',
          tilePadding: 0,
          patternScale: 1,
          warpStrength: 1,
          cellularScale: 1,
          cellularJitter: 1,
          stepsCount: 5,
          seed: 0,
          noiseStyle: 'linear',
          noiseThreshold: 0,
          imageWidth: 1,
          imageHeight: 1,
          microFreq: 0,
          imageInvertColor: false,
          imageInvertOpacity: false,
          imageId: '',
          imageName: '',
          imagePreview: '',
          imageAlgo: 'luma',
          imageEffects: [
            {
              id: 'effect-1',
              enabled: true,
              mode: 'luma',
              imageBrightness: 0,
              imageLevelsLow: 0,
              imageLevelsHigh: 1,
              imageEmbossStrength: 1,
              imageSharpenAmount: 1,
              imageSharpenRadius: 1,
              imageMedianRadius: 1,
              imageGamma: 1,
              imageContrast: 1,
              imageSolarize: 0.5,
              imagePixelate: 12,
              imageDither: 0.5,
              imageThreshold: 0.5,
              imagePosterize: 5,
              imageBlur: 0,
              imageBlurRadius: 0,
              imageBlurStrength: 1,
              imageEdgeBlur: 0,
              imageHighpassRadius: 1,
              imageHighpassStrength: 1,
              imageLowpassRadius: 2,
              imageLowpassStrength: 0.6,
              imageVignetteStrength: 0.4,
              imageVignetteRadius: 0.85,
              imageCurveStrength: 0.4,
              imageBandCenter: 0.5,
              imageBandWidth: 0.3,
            },
          ],
          polygonZoomReference: 0.01,
          polygonRadius: 2,
          polygonSides: 6,
          polygonRotation: 0,
          polygonOutline: 0,
          polygonEdgeRadius: 0,
        },
      ],
      smoothing: 0,
      simplify: 0,
      curves: true,
    },
    spirograph: {
      label: 'Spirograph',
      preset: 'spirograph-default',
      mainShape: 'polygon',
      mainWidth: 140,
      mainHeight: 140,
      mainCornerRadius: 17.5,
      mainPoints: 6,
      mainTeeth: 240,
      gearShape: 'circle',
      gearTeeth: 59,
      gearAspectX: 100,
      gearAspectY: 100,
      gearCornerRadius: 0,
      gearPoints: 6,
      penAngle: 0,
      penOffset: 83,
      rollMode: 'both',
      curveResolution: 1200,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    spiralizer: {
      label: 'Spiralizer',
      is3d: true,
      preset: 'spiralizer-default',
      shape: 'helix',
      sphereRadius: 64,
      baseRadius: 68,
      coneHeight: 136,
      cylinderRadius: 58,
      cylinderHeight: 156,
      ellipsoidEquatorRadius: 76,
      ellipsoidPolarRadius: 52,
      torusRingRadius: 64,
      torusTubeRadius: 26,
      capsuleRadius: 46,
      capsuleHeight: 120,
      helixRadius: 48,
      helixHeight: 168,
      helixCount: 1,
      helixRungs: true,
      helixRungSpacing: 10,
      helixGrooveOffset: 160,
      surfaceMode: 'seeThrough',
      outlineMode: 'none',
      wrapType: 'spiral',
      renderStyle: 'line',
      thickness: '1',
      turns: 3,
      twistTurns: 6,
      lineCount: 16,
      dotSpacing: 14,
      // Universal Fill dropdown for hollow markers (dots / squares / triangles).
      markerFill: 'none',
      fillDensity: 4,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillDotSize: 1.0,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillDotShape: 'circle',
      fillDotJitter: 0,
      fillLineCount: 1,
      fillSpiralTightness: 0,
      fillSpiralDirection: 'cw',
      fillRadialSkip: 0,
      fillWaveSmoothing: 1.0,
      fillWaveFrequency: 1.0,
      dotSizeStart: 4,
      dotSizeMiddle: 4,
      dotSizeEnd: 4,
      startLongitude: 0,
      yaw: 0,
      pitch: 30,
      roll: 0,
      curveResolution: 900,
      projection: 'orthographic',
      cameraDistance: 620,
      focalLength: 520,
      depthCue: 'off',
      depthCueStrength: 60,
      emphasizeOutline: false,
      outlineWeight: 2,
      showCreases: false,
      creaseAngle: 35,
      hiddenLineMode: 'backface',
      depthBias: 0.5,
      hatchEnable: false,
      lightAzimuth: 135,
      lightElevation: 45,
      hatchAngle: 45,
      hatchSpacing: 6,
      crossHatch: false,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    polyhedron: {
      label: 'Polyhedron',
      is3d: true,
      preset: 'polyhedron-default',
      solidType: 'buckyball',
      importedMesh: null,
      meshName: '',
      sideCount: 5,
      frequency: 2,
      taper: 55,
      starRatio: 45,
      radius: 76,
      depth: 94,
      surfaceMode: 'front',
      faceOpacityMode: 'seeThrough',
      showFaces: true,
      faceBands: 4,
      showEdges: true,
      edgeStyle: 'dash',
      edgeSpacing: 11,
      showVertices: true,
      vertexOcclusionMode: 'outline',
      vertexSize: 4.2,
      vertexRings: 1,
      bulge: 10,
      extrude: 0,
      explode: 0,
      expand: 100,
      shard: 0,
      twist: 0,
      rotate: -18,
      tilt: 28,
      projection: 'orthographic',
      cameraDistance: 620,
      focalLength: 520,
      depthCue: 'off',
      depthCueStrength: 60,
      emphasizeOutline: false,
      outlineWeight: 2,
      showCreases: false,
      creaseAngle: 35,
      hiddenLineMode: 'backface',
      depthBias: 0.5,
      hatchEnable: false,
      lightAzimuth: 135,
      lightElevation: 45,
      hatchAngle: 45,
      hatchSpacing: 6,
      crossHatch: false,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    topoform: {
      label: 'Topoform',
      is3d: true,
      preset: 'topoform-default',
      sourceMode: 'sphere',
      importedMesh: null,
      meshName: '',
      renderMode: 'contours',
      primitiveDetail: 18,
      primitiveScaleX: 65,
      primitiveScaleY: 65,
      primitiveScaleZ: 65,
      simplifyMesh: 0,
      lineCount: 26,
      planeRotate: 0,
      planeTilt: 0,
      contourVisibility: 'visibleOnly',
      contourSmoothing: 0,
      showOutline: true,
      yaw: -28,
      pitch: 34,
      roll: 0,
      projection: 'orthographic',
      cameraDistance: 620,
      focalLength: 520,
      sceneLighting: false,
      specularHighlight: false,
      specularSize: 35,
      depthCue: 'off',
      depthCueStrength: 60,
      emphasizeOutline: false,
      outlineWeight: 2,
      showCreases: false,
      creaseAngle: 35,
      hiddenLineMode: 'backface',
      depthBias: 0.5,
      hatchEnable: false,
      lightAzimuth: 135,
      lightElevation: 45,
      hatchAngle: 45,
      hatchSpacing: 6,
      crossHatch: false,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    rasterPlane: {
      label: 'Raster-Plane',
      is3d: true,
      preset: 'rasterplane-default',
      mode: 'lines',
      // Source: 'builtin' procedural relief by default. The source widget swaps
      // this for a 'noise' preset (re-rendered from imageNoiseDef), an
      // 'imported' image, or a 'painted' canvas (both embedded as imageSrc).
      imageSourceKind: 'builtin',
      imageName: 'Built-in Relief',
      imageNoiseDef: null,
      imageSeed: 1,
      imageSrc: '',
      imageId: '',
      mapType: 'height',
      normalFlipY: false,
      clipBlackAreas: false,
      artworkSize: 150,
      amplitude: 10,
      sampleDetail: 84,
      // Map Blur blurs the sampled height field before projection (topography
      // mode only). Distinct from the universal output-line `smoothing` below.
      mapBlur: 18,
      invert: false,
      gamma: 1,
      contrast: 0,
      // Surface Noise: the universal noise rack stack (`noises`) is sampled live
      // and embossed onto the height field. Each layer's own Blend Mode + Field
      // Weight drive the displacement — there is no global noise mode/amount.
      // The stack starts empty so surfaces render unchanged until a layer is added.
      noises: [],
      rotate: -45,
      tilt: 60,
      rows: 42,
      columns: 28,
      horizontalLineAngle: 0,
      horizontalLinesAsPlanes: false,
      // Base Height (Lines as Planes only): constant lift added to every slice.
      baseHeight: 0,
      // Plane Width (Lines as Planes only): each slice's thickness as a % of the
      // row pitch. 100 = slices touch and merge into a solid slab; lower values
      // shrink each slice into a free-standing extruded plane with real gaps.
      planeWidth: 100,
      seeThrough: true,
      topographyAngle: 0,
      contourSmoothing: 20,
      barRows: 14,
      barColumns: 14,
      barGap: 0,
      barHeightSteps: 6,
      showBarBase: true,
      barSides: 4,
      barRotate: 0,
      barCornerRadius: 0,
      projection: 'orthographic',
      cameraDistance: 620,
      focalLength: 520,
      depthCue: 'off',
      depthCueStrength: 60,
      emphasizeOutline: false,
      outlineWeight: 2,
      showCreases: false,
      creaseAngle: 35,
      hiddenLineMode: 'backface',
      depthBias: 0.5,
      hatchEnable: false,
      lightAzimuth: 135,
      lightElevation: 45,
      hatchAngle: 45,
      hatchSpacing: 6,
      crossHatch: false,
      // Universal output controls: Smoothing (post-projection line smoothing) +
      // Simplify + Curves all apply to the projected wire output.
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    shape: {
      label: 'Shape',
      hidden: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    group: {
      label: 'Group',
      hidden: true,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
    svgDistort: {
      label: 'SVG Import',
      preset: 'svgdistort-default',
      importedGroups: [],
      svgName: '',
      showOutlines: true,
      fillMode: 'hatch',
      fillDensity: 8,
      fillAngle: 0,
      fillAmplitude: 1.0,
      fillDotSize: 1.0,
      fillPadding: 0,
      fillShiftX: 0,
      fillShiftY: 0,
      fillDotPattern: 'brick',
      fillAxes: 3,
      autoFit: true,
      scale: 1.0,
      offsetX: 0,
      offsetY: 0,
      noises: [],
      noiseTarget: 'all',
      seed: 0,
      smoothing: 0,
      simplify: 0,
      curves: false,
    },
  };

  // Canonical section order for the algorithm pickers. Typography and Image
  // algorithms get their own section header after the dimensional groups.
  window.Vectura.ALGO_CATEGORY_ORDER = ['2D', '3D', 'Typography', 'Image'];

  // Group a list of picker items ([{ type, label, is3d? }, …]) into ordered
  // sections for the algorithm menus. Shared by all three picker surfaces so the
  // section headers stay in lock-step. Returns [{ label, items: [...] }, …].
  window.Vectura.groupAlgorithmsForMenu = (items) => {
    const A = window.Vectura.ALGO_DEFAULTS || {};
    const order = window.Vectura.ALGO_CATEGORY_ORDER || ['2D', '3D'];
    const buckets = new Map();
    (items || []).forEach((item) => {
      const def = A[item.type] || {};
      const category = def.category || ((def.is3d || item.is3d) ? '3D' : '2D');
      if (!buckets.has(category)) buckets.set(category, []);
      buckets.get(category).push(item);
    });
    const ordered = [];
    order.forEach((category) => {
      if (buckets.has(category)) {
        ordered.push({ label: category, items: buckets.get(category) });
        buckets.delete(category);
      }
    });
    // Any categories not in the canonical order trail alphabetically.
    Array.from(buckets.keys()).sort().forEach((category) => {
      ordered.push({ label: category, items: buckets.get(category) });
    });
    return ordered;
  };

  window.Vectura.SETTINGS = {
    uiTheme: 'dark',
    margin: 20,
    speedDown: 250,
    speedUp: 300,
    precision: 3,
    strokeWidth: 0.3,
    strokeWidthOverride: false,
    bgColor: '#121214',
    undoSteps: 20,
    truncate: true,
    cropExports: true,
    removeHiddenGeometry: true,
    outsideOpacity: 0.5,
    marginLineVisible: false,
    marginLineWeight: 0.2,
    marginLineColor: '#52525b',
    marginLineDotting: 0,
    showGuides: true,
    snapGuides: true,
    // Contextual Task Bar (Illustrator parity, Phase 2). Enabled by default; the
    // position/pinned bag is populated lazily by src/ui/shell/context-bar.js.
    contextBarEnabled: true,
    contextBar: { pinned: false, x: null, y: null },
    selectionOutline: true,
    selectionOutlineColor: '#ef4444',
    selectionOutlineWidth: 0.15,
    selectionOutlineHide3d: true,
    gridType: 'none',
    gridOpacity: 0.2,
    gridStyle: 'cartesian',
    gridColor: '#ffffff',
    gridSize: 10,
    gridMinorOpacity: 0.08,
    gridMinorColor: '#ffffff',
    gridMinorSize: 5,
    gridSnapEnabled: false,
    gridSnapSensitivity: 50,
    uiSections: {
      algorithm: false,
      algorithmTransform: true,
      algorithmConfiguration: false,
      pathfinder: true,
    },
    aboutVisible: true,
    touchModifiers: {
      shift: false,
      alt: false,
      meta: false,
      ctrl: false,
      pan: false,
    },
    documentUnits: 'metric',
    // Live X/Y coordinate readout chip shown while hovering/dragging anchors and
    // handles (Settings ▸ Guides & Display ▸ "Coordinate readout"). Default ON.
    showCoordinateReadout: true,
    // Center helper point (blue diamond + "center" label + X/Y chip) revealed
    // when hovering any object's center (Settings ▸ Guides & Display). Default ON.
    showCenterPoint: true,
    paperSize: 'letter',
    paperWidth: 216,
    paperHeight: 279,
    paperOrientation: 'landscape',
    showDocumentDimensions: false,
    // Fidelity of the live regen while a 3D layer is dragged/transformed.
    // 'draft' = fastest/coarsest, 'high' = near-final. Consumed by the 3D
    // algorithms via bounds.preview3dQuality (see Geometry3D.previewDetailScale).
    preview3dQuality: 'balanced',
    optimizationScope: 'all',
    optimizationPreview: 'off',
    // Canvas line-sort overlay (the eye toggle on the Draw Order subpanel). Kept
    // separate from optimizationPreview — and intentionally NOT persisted — so the
    // overlay is closed by default on every load and only opens when the user clicks
    // the eye, regardless of export/optimization-preview state.
    lineSortOverlayVisible: false,
    optimizationExport: true,
    optimizationOverlayColor: '#EE00FF',
    // Overlay end (print-order) colour. '' = auto (per-layer line-sort secondary, else
    // the start colour's complement). Set via the canvas legend gear's End Color.
    optimizationOverlaySecondaryColor: '#00FBFF',
    optimizationOverlayWidth: 0.2,
    activeTool: 'select',
    penMode: 'draw',
    scissorMode: 'line',
    shapeMode: 'oval',
    cookiePreferencesEnabled: false,
    showCrystallographicNames: false,
    devMode: false,
    wallpaperPanelMode: 'styles',
    paneLeftWidth: 335,
    paneRightWidth: 335,
    lightSource: null,
    optimizationDefaults: {
      bypassAll: false,
      steps: [
        { id: 'linesimplify', enabled: true, bypass: false, tolerance: 0.2, mode: 'curve' },
        { id: 'linesort', enabled: true, bypass: false, method: 'asdrawn', direction: 'none', grouping: 'combined' },
        { id: 'filter', enabled: false, bypass: false, minLength: 0, maxLength: 800, removeTiny: true },
        { id: 'multipass', enabled: false, bypass: false, passes: 2, offset: 0.2, jitter: 0, seed: 0 },
      ],
    },
    plotterOptimize: 0,
    paletteId: 'blues-01',
    autoColorization: {
      enabled: false,
      scope: 'all',
      mode: 'none',
      params: {
        penOffset: 0,
        penStride: 1,
        penMirror: false,
        penJitter: 0,
        radiusStart: 0,
        radiusEnd: 100,
        bandSize: 20,
        bandOffset: 0,
        bandGrowth: 0,
        bandStart: 0,
        bandEnd: 100,
        angleOffset: 0,
        angleSpan: 360,
        spiralTurns: 1,
        sizeCurve: 1,
        sizeInvert: false,
        randomSeed: 1,
      },
    },
    autoColorizationCollapsed: true,
    pensCollapsed: false,
    pens: [
      { id: 'pen-1', name: 'Pen 1', color: '#ffffff', width: 0.3 },
      { id: 'pen-2', name: 'Pen 2', color: '#dbeafe', width: 0.5 },
      { id: 'pen-3', name: 'Pen 3', color: '#93c5fd', width: 0.8 },
    ],
    globalLayerCount: 0,
    layerBarPaletteId: 'prism',
    showTourOnFirstLaunch: false,
    tourSeen: false,
    toolbarDock: null,
    toolbarX: null,
    toolbarY: null,
    toolbarLocked: false,
    toolbarHorizontal: false,
  };
  window.Vectura.NOISE_IMAGES = window.Vectura.NOISE_IMAGES || {};

  window.Vectura.LAYER_PALETTES = [
    {
      id: 'prism',
      name: 'Prism',
      preview: ['#60A5FA', '#A78BFA', '#34D399', '#F59E0B', '#EC4899', '#FB923C'],
      colors: {
        flowfield: '#60A5FA', wavetable: '#A78BFA', rings: '#EC4899',
        hyphae: '#34D399', topo: '#22D3EE', grid: '#94A3B8',
        spiral: '#F59E0B', boids: '#FB923C', attractor: '#F87171',
        lissajous: '#C084FC', harmonograph: '#818CF8', rainfall: '#38BDF8',
        phylla: '#4ADE80', shapePack: '#FBBF24', petalisDesigner: '#E879F9',
        pattern: '#2DD4BF', svgDistort: '#FCA5A5', terrain: '#86EFAC',
        horizon: '#93C5FD', spirograph: '#14B8A6', spiralizer: '#8B5CF6',
        polyhedron: '#F472B6', topoform: '#06B6D4', rasterPlane: '#F59E0B',
        text: '#A3E635', halftone: '#FB7185', imageWeave: '#5EEAD4',
        _group: '#6B7280', _pen: '#9CA3AF', _default: '#A1A1AA',
      },
    },
    {
      id: 'neon',
      name: 'Neon',
      preview: ['#00F5FF', '#FF00FF', '#00FF66', '#FFD600', '#FF4081', '#FF6D00'],
      colors: {
        flowfield: '#00F5FF', wavetable: '#FF00FF', rings: '#FF007A',
        hyphae: '#00FF66', topo: '#00FFCC', grid: '#E0E0E0',
        spiral: '#FFD600', boids: '#FF6D00', attractor: '#FF3D00',
        lissajous: '#D500F9', harmonograph: '#651FFF', rainfall: '#00B0FF',
        phylla: '#69FF47', shapePack: '#FFFF00', petalisDesigner: '#FF1744',
        pattern: '#1DE9B6', svgDistort: '#FF9100', terrain: '#B2FF59',
        horizon: '#40C4FF', spirograph: '#00FFCC', spiralizer: '#7C4DFF',
        polyhedron: '#FF00AA', topoform: '#00B8D4', rasterPlane: '#FFD600',
        text: '#76FF03', halftone: '#FF4081', imageWeave: '#18FFFF',
        _group: '#78909C', _pen: '#B0BEC5', _default: '#BDBDBD',
      },
    },
    {
      id: 'pastel',
      name: 'Pastel',
      preview: ['#93C5FD', '#C4B5FD', '#6EE7B7', '#FCD34D', '#F9A8D4', '#FCA5A5'],
      colors: {
        flowfield: '#93C5FD', wavetable: '#C4B5FD', rings: '#F9A8D4',
        hyphae: '#6EE7B7', topo: '#67E8F9', grid: '#CBD5E1',
        spiral: '#FCD34D', boids: '#FCA5A5', attractor: '#FBBF24',
        lissajous: '#DDD6FE', harmonograph: '#A5B4FC', rainfall: '#BAE6FD',
        phylla: '#BBF7D0', shapePack: '#FEF08A', petalisDesigner: '#FBCFE8',
        pattern: '#99F6E4', svgDistort: '#FED7AA', terrain: '#D9F99D',
        horizon: '#E0E7FF', spirograph: '#5EEAD4', spiralizer: '#C4B5FD',
        polyhedron: '#F9A8D4', topoform: '#67E8F9', rasterPlane: '#FDE68A',
        text: '#BEF264', halftone: '#FDA4AF', imageWeave: '#A5F3FC',
        _group: '#9CA3AF', _pen: '#D1D5DB', _default: '#E5E7EB',
      },
    },
    {
      id: 'ember',
      name: 'Ember',
      preview: ['#F97316', '#EF4444', '#D97706', '#FBBF24', '#84CC16', '#B45309'],
      colors: {
        flowfield: '#F97316', wavetable: '#EF4444', rings: '#DC2626',
        hyphae: '#84CC16', topo: '#D97706', grid: '#78716C',
        spiral: '#FBBF24', boids: '#B45309', attractor: '#9A3412',
        lissajous: '#C2410C', harmonograph: '#7C3AED', rainfall: '#CA8A04',
        phylla: '#4D7C0F', shapePack: '#A16207', petalisDesigner: '#BE185D',
        pattern: '#0F766E', svgDistort: '#EA580C', terrain: '#65A30D',
        horizon: '#F59E0B', spirograph: '#2DD4BF', spiralizer: '#A855F7',
        polyhedron: '#E11D48', topoform: '#CA8A04', rasterPlane: '#FBBF24',
        text: '#A3E635', halftone: '#F43F5E', imageWeave: '#0D9488',
        _group: '#6B7280', _pen: '#9CA3AF', _default: '#78716C',
      },
    },
    {
      id: 'ocean',
      name: 'Ocean',
      preview: ['#38BDF8', '#818CF8', '#06B6D4', '#14B8A6', '#3B82F6', '#8B5CF6'],
      colors: {
        flowfield: '#38BDF8', wavetable: '#818CF8', rings: '#8B5CF6',
        hyphae: '#06B6D4', topo: '#0891B2', grid: '#64748B',
        spiral: '#3B82F6', boids: '#60A5FA', attractor: '#7C3AED',
        lissajous: '#2563EB', harmonograph: '#4F46E5', rainfall: '#0EA5E9',
        phylla: '#14B8A6', shapePack: '#0284C7', petalisDesigner: '#A855F7',
        pattern: '#22D3EE', svgDistort: '#6366F1', terrain: '#4ADE80',
        horizon: '#BAE6FD', spirograph: '#2DD4BF', spiralizer: '#A78BFA',
        polyhedron: '#F472B6', topoform: '#06B6D4', rasterPlane: '#FACC15',
        text: '#5EEAD4', halftone: '#C084FC', imageWeave: '#67E8F9',
        _group: '#64748B', _pen: '#94A3B8', _default: '#6366F1',
      },
    },
    {
      id: 'dusk',
      name: 'Dusk',
      preview: ['#EC4899', '#A855F7', '#F97316', '#FBBF24', '#FB7185', '#8B5CF6'],
      colors: {
        flowfield: '#F97316', wavetable: '#F472B6', rings: '#EC4899',
        hyphae: '#A78BFA', topo: '#8B5CF6', grid: '#9CA3AF',
        spiral: '#FBBF24', boids: '#FB923C', attractor: '#E11D48',
        lissajous: '#A855F7', harmonograph: '#7C3AED', rainfall: '#FCA5A5',
        phylla: '#4ADE80', shapePack: '#FCD34D', petalisDesigner: '#DB2777',
        pattern: '#FB7185', svgDistort: '#FDBA74', terrain: '#86EFAC',
        horizon: '#FDE68A', spirograph: '#14B8A6', spiralizer: '#C084FC',
        polyhedron: '#FB7185', topoform: '#38BDF8', rasterPlane: '#F59E0B',
        text: '#FCD34D', halftone: '#F43F5E', imageWeave: '#22D3EE',
        _group: '#6B7280', _pen: '#9CA3AF', _default: '#F97316',
      },
    },
    {
      id: 'forest',
      name: 'Forest',
      preview: ['#4ADE80', '#22C55E', '#86EFAC', '#BEF264', '#2DD4BF', '#84CC16'],
      colors: {
        flowfield: '#4ADE80', wavetable: '#22C55E', rings: '#86EFAC',
        hyphae: '#15803D', topo: '#0F766E', grid: '#84CC16',
        spiral: '#A3E635', boids: '#16A34A', attractor: '#065F46',
        lissajous: '#6EE7B7', harmonograph: '#34D399', rainfall: '#14B8A6',
        phylla: '#BBF7D0', shapePack: '#BEF264', petalisDesigner: '#4ADE80',
        pattern: '#2DD4BF', svgDistort: '#D9F99D', terrain: '#854D0E',
        horizon: '#A7F3D0', spirograph: '#2DD4BF', spiralizer: '#A78BFA',
        polyhedron: '#F9A8D4', topoform: '#22D3EE', rasterPlane: '#BEF264',
        text: '#65A30D', halftone: '#FCD34D', imageWeave: '#5EEAD4',
        _group: '#6B7280', _pen: '#A1A1AA', _default: '#22C55E',
      },
    },
    {
      id: 'mono',
      name: 'Mono',
      preview: ['#FAFAFA', '#D4D4D8', '#A1A1AA', '#71717A', '#52525B', '#3F3F46'],
      colors: {
        flowfield: '#FAFAFA', wavetable: '#E4E4E7', rings: '#D4D4D8',
        hyphae: '#A1A1AA', topo: '#71717A', grid: '#52525B',
        spiral: '#F4F4F5', boids: '#E4E4E7', attractor: '#3F3F46',
        lissajous: '#D4D4D8', harmonograph: '#A1A1AA', rainfall: '#71717A',
        phylla: '#F4F4F5', shapePack: '#E4E4E7', petalisDesigner: '#D4D4D8',
        pattern: '#A1A1AA', svgDistort: '#71717A', terrain: '#52525B',
        horizon: '#FAFAFA', spirograph: '#D4D4D8', spiralizer: '#E4E4E7',
        polyhedron: '#A1A1AA', topoform: '#71717A', rasterPlane: '#F4F4F5',
        text: '#E4E4E7', halftone: '#D4D4D8', imageWeave: '#71717A',
        _group: '#6B7280', _pen: '#A1A1AA', _default: '#A1A1AA',
      },
    },
    {
      id: 'candy',
      name: 'Candy',
      preview: ['#FF6B9D', '#A855F7', '#00E5CC', '#FFD600', '#FF6E40', '#69F0AE'],
      colors: {
        flowfield: '#FF6B9D', wavetable: '#A855F7', rings: '#FF4081',
        hyphae: '#00E5CC', topo: '#FFD600', grid: '#69F0AE',
        spiral: '#FF9100', boids: '#40C4FF', attractor: '#E040FB',
        lissajous: '#FFFF00', harmonograph: '#1DE9B6', rainfall: '#00B0FF',
        phylla: '#B2FF59', shapePack: '#FFD740', petalisDesigner: '#FF6E40',
        pattern: '#76FF03', svgDistort: '#FFAB40', terrain: '#00E676',
        horizon: '#64FFDA', spirograph: '#00E5CC', spiralizer: '#A855F7',
        polyhedron: '#FF6B9D', topoform: '#40C4FF', rasterPlane: '#FFD600',
        text: '#76FF03', halftone: '#FF4081', imageWeave: '#18FFFF',
        _group: '#78909C', _pen: '#B0BEC5', _default: '#FF6B9D',
      },
    },
    {
      id: 'pen-color',
      name: 'Pen Color',
      preview: null,
      colors: null,
    },
  ];
})();
