/**
 * Algorithm descriptions for the UI.
 */
(() => {
  window.Vectura = window.Vectura || {};
  window.Vectura.DESCRIPTIONS = {
    flowfield:
      'Particles traverse a vector field generated by Simplex noise. Creates organic, fluid-like textures resembling hair or flowing water.',
    lissajous:
      'Parametric curves created by the intersection of two sinusoidal waves. Produces elegant, looping harmonic figures often used in signal physics.',
    wavetable:
      'Generates terrain-like elevations by modulating horizontal lines with noise. Inspired by the visualization of pulsar radio waves.',
    spiral:
      'An Archimedean spiral distorted by noise. Can create vinyl-like grooves or organic coil patterns.',
    grid:
      'A rectilinear mesh deformed by noise fields. Supports warping vertices or displacing rows/cols for glitch effects.',
    phylla:
      'Arranges points in a spiral pattern based on the golden angle (137.5°). Mimics seed heads in sunflowers and succulents.',
    boids:
      'Simulates the flocking behavior of birds (Agents). Rules for Separation, Alignment, and Cohesion create complex emergent movement trails.',
    attractor:
      'Plots Strange Attractors (Lorenz, Aizawa). These represent chaotic systems where trajectories orbit a fractal set of states.',
    hyphae:
      'Simulates organic growth (like fungi or roots) using a branching algorithm. Sources grow segments and fork based on probability.',
    shapePack:
      'Packs non-overlapping shapes that can be perfect circles or regular polygons. Supports rotation and perspective warping for angular forms.',
  };
})();
