/**
 * Algorithm descriptions for the UI.
 */
(() => {
  window.Vectura = window.Vectura || {};
  window.Vectura.DESCRIPTIONS = {
    flowfield:
      'Particles traverse a vector field generated by Simplex noise. Creates organic, fluid-like textures resembling hair or flowing water.',
    lissajous:
      'Parametric curves created by the intersection of two sinusoidal waves. Produces elegant, looping harmonic figures often used in signal physics.',
    harmonograph:
      'Generates damped, multi-pendulum curves by combining decaying sine waves along the X and Y axes.',
    wavetable:
      'Generates terrain-like elevations by modulating horizontal lines with one or more stacked noise sources. Inspired by the visualization of pulsar radio waves.',
    rings:
      'Creates concentric rings with noise-driven radius modulation for organic, rippling shapes.',
    topo:
      'Builds contour lines from a noise-based height field, similar to a topographic map.',
    petalis:
      'Generates layered radial petals with adjustable geometry, spiral distribution, center morphing, and shading.',
    petalisDesigner:
      'Petalis variant with an embedded Petal Designer panel for direct outer/inner profile drawing and live shading iteration.',
    rainfall:
      'Simulates falling rain traces with optional droplet shapes, wind influence, and silhouette masking.',
    spiral:
      'An Archimedean spiral distorted by noise. Can create vinyl-like grooves or organic coil patterns.',
    grid:
      'A rectilinear mesh deformed by noise fields. Supports warping vertices or displacing rows/cols for glitch effects.',
    phylla:
      'Arranges points in a spiral pattern based on the golden angle (137.5°). Mimics seed heads in sunflowers and succulents.',
    boids:
      'Simulates the flocking behavior of birds (Agents). Rules for Separation, Alignment, and Cohesion create complex emergent movement trails.',
    attractor:
      'Plots Strange Attractors (Lorenz, Aizawa). These represent chaotic systems where trajectories orbit a fractal set of states.',
    hyphae:
      'Simulates organic growth (like fungi or roots) using a branching algorithm. Sources grow segments and fork based on probability.',
    shapePack:
      'Packs non-overlapping shapes that can be perfect circles or regular polygons. Supports perspective warping for angular forms.',
    expanded:
      'Static sublayer created from an expanded generation. Use transform and common controls to refine the line.',
    group: 'Group container for expanded line sublayers.',
  };
})();
