(() => {
  'use strict';
  // Auto-generated by scripts/build-user-presets.js — do not edit manually.
  // To add presets: drop .vectura files into user-presets/pendula/ or
  // user-presets/harmonograph/, then run: npm run user-presets:bundle
  const Vectura = (window.Vectura = window.Vectura || {});
  if (!Array.isArray(Vectura.PRESETS)) Vectura.PRESETS = [];
  Vectura.PRESETS.push(...[]);
})();
