(() => {
  'use strict';
  // Auto-generated by scripts/build-user-presets.js — do not edit manually.
  // The user-presets/ file tree is the single source of truth for the preset
  // library. To add/edit presets: drop or edit .vectura files in
  // user-presets/<algorithm>/ (directory name == layer type), then run:
  //   npm run user-presets:bundle
  const Vectura = (window.Vectura = window.Vectura || {});
  if (!Array.isArray(Vectura.PRESETS)) Vectura.PRESETS = [];
  Vectura.PRESETS.push(...[
      {
        "id": "attractor-default",
        "name": "Default",
        "preset_system": "attractor",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "boids-default",
        "name": "Default",
        "preset_system": "boids",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "flowfield-default",
        "name": "Default",
        "preset_system": "flowfield",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "grid-default",
        "name": "Default",
        "preset_system": "grid",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "harmonograph-default",
        "name": "Default",
        "preset_system": "harmonograph",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "hyphae-default",
        "name": "Default",
        "preset_system": "hyphae",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "imagesurface-default",
        "name": "Default",
        "preset_system": "imageSurface",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "lissajous-default",
        "name": "Default",
        "preset_system": "lissajous",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "meshtopography-default",
        "name": "Default",
        "preset_system": "meshTopography",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "pendula-default",
        "name": "Default",
        "preset_system": "pendula",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "petalisdesigner-default",
        "name": "Default",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "polyhedron-default",
        "name": "Default",
        "preset_system": "polyhedron",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "rainfall-default",
        "name": "Default",
        "preset_system": "rainfall",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "rings-default",
        "name": "Default",
        "preset_system": "rings",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "shapepack-default",
        "name": "Default",
        "preset_system": "shapePack",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "spiral-default",
        "name": "Default",
        "preset_system": "spiral",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "spiral3d-default",
        "name": "Default",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "spirograph-default",
        "name": "Default",
        "preset_system": "spirograph",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "svgdistort-default",
        "name": "Default",
        "preset_system": "svgDistort",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "terrain-default",
        "name": "Default",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {}
      },
      {
        "id": "attractor-aizawa-shell",
        "name": "Aizawa Shell",
        "preset_system": "attractor",
        "group": "Classic",
        "params": {
          "type": "aizawa",
          "iter": 3000,
          "scale": 5,
          "dt": 0.01
        }
      },
      {
        "id": "attractor-dense-lorenz",
        "name": "Dense Lorenz",
        "preset_system": "attractor",
        "group": "Complex",
        "params": {
          "type": "lorenz",
          "iter": 5000,
          "scale": 3,
          "dt": 0.005,
          "sigma": 10,
          "rho": 28,
          "beta": 2.66
        }
      },
      {
        "id": "attractor-lorenz-butterfly",
        "name": "Lorenz Butterfly",
        "preset_system": "attractor",
        "group": "Classic",
        "params": {
          "type": "lorenz",
          "iter": 2000,
          "scale": 3,
          "dt": 0.01,
          "sigma": 10,
          "rho": 28,
          "beta": 2.66
        }
      },
      {
        "id": "attractor-sparse-web",
        "name": "Sparse Web",
        "preset_system": "attractor",
        "group": "Geometric",
        "params": {
          "type": "lorenz",
          "iter": 600,
          "scale": 6,
          "dt": 0.02,
          "sigma": 10,
          "rho": 28,
          "beta": 2.66
        }
      },
      {
        "id": "boids-murmuration",
        "name": "Murmuration",
        "preset_system": "boids",
        "group": "Complex",
        "params": {
          "count": 400,
          "steps": 200,
          "speed": 2,
          "mode": "birds",
          "sepWeight": 1.2,
          "alignWeight": 1,
          "cohWeight": 1
        }
      },
      {
        "id": "boids-scatter-field",
        "name": "Scatter Field",
        "preset_system": "boids",
        "group": "Organic",
        "params": {
          "count": 200,
          "steps": 100,
          "speed": 2.5,
          "mode": "birds",
          "sepWeight": 2.2,
          "alignWeight": 0.5,
          "cohWeight": 0.4,
          "sepDist": 16
        }
      },
      {
        "id": "boids-schooling-fish",
        "name": "Schooling Fish",
        "preset_system": "boids",
        "group": "Classic",
        "params": {
          "count": 120,
          "steps": 140,
          "speed": 2,
          "mode": "fish",
          "sepWeight": 1,
          "alignWeight": 1.2,
          "cohWeight": 1.3,
          "cohDist": 28
        }
      },
      {
        "id": "boids-squadron",
        "name": "Squadron",
        "preset_system": "boids",
        "group": "Classic",
        "params": {
          "count": 80,
          "steps": 120,
          "speed": 2.2,
          "mode": "birds",
          "sepWeight": 0.8,
          "alignWeight": 1.5,
          "cohWeight": 0.9,
          "alignDist": 30
        }
      },
      {
        "id": "flowfield-river-current",
        "name": "River Current",
        "preset_system": "flowfield",
        "group": "Classic",
        "params": {
          "flowMode": "angle",
          "density": 1200,
          "chaos": 0.15,
          "stepLen": 6,
          "maxSteps": 260,
          "force": 1.2,
          "octaves": 2
        }
      },
      {
        "id": "flowfield-still-pool",
        "name": "Still Pool",
        "preset_system": "flowfield",
        "group": "Classic",
        "params": {
          "flowMode": "angle",
          "density": 800,
          "chaos": 0.05,
          "stepLen": 5,
          "maxSteps": 220,
          "force": 1,
          "octaves": 2
        }
      },
      {
        "id": "flowfield-storm-cell",
        "name": "Storm Cell",
        "preset_system": "flowfield",
        "group": "Complex",
        "params": {
          "flowMode": "angle",
          "density": 2000,
          "chaos": 0.5,
          "stepLen": 7,
          "maxSteps": 300,
          "force": 1.4,
          "octaves": 3
        }
      },
      {
        "id": "flowfield-whirlpool",
        "name": "Whirlpool",
        "preset_system": "flowfield",
        "group": "Geometric",
        "params": {
          "flowMode": "curl",
          "density": 1000,
          "chaos": 0.06,
          "stepLen": 5,
          "maxSteps": 240,
          "force": 1,
          "octaves": 2
        }
      },
      {
        "id": "grid-chaos-mesh",
        "name": "Chaos Mesh",
        "preset_system": "grid",
        "group": "Complex",
        "params": {
          "rows": 25,
          "cols": 25,
          "distortion": 30,
          "chaos": 8,
          "type": "warp"
        }
      },
      {
        "id": "grid-graph-paper",
        "name": "Graph Paper",
        "preset_system": "grid",
        "group": "Geometric",
        "params": {
          "rows": 20,
          "cols": 20,
          "distortion": 2,
          "chaos": 0,
          "type": "warp"
        }
      },
      {
        "id": "grid-shift-tile",
        "name": "Shift Tile",
        "preset_system": "grid",
        "group": "Geometric",
        "params": {
          "rows": 12,
          "cols": 12,
          "distortion": 8,
          "chaos": 0,
          "type": "shift"
        }
      },
      {
        "id": "grid-warp-field",
        "name": "Warp Field",
        "preset_system": "grid",
        "group": "Organic",
        "params": {
          "rows": 16,
          "cols": 16,
          "distortion": 15,
          "chaos": 0,
          "type": "warp"
        }
      },
      {
        "id": "harmonograph-4-3-star",
        "name": "4:3 Star",
        "preset_system": "harmonograph",
        "group": "Geometric",
        "params": {
          "renderMode": "line",
          "duration": 40,
          "scale": 0.5,
          "loopDrift": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 100,
              "ampY": 0,
              "phaseX": 90,
              "phaseY": 0,
              "freq": 4,
              "micro": 0.005,
              "damp": 0.0012
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 0,
              "ampY": 100,
              "phaseX": 0,
              "phaseY": 0,
              "freq": 3,
              "micro": 0.005,
              "damp": 0.0012
            }
          ]
        }
      },
      {
        "id": "harmonograph-classic-3-2-star",
        "name": "Classic 3:2 Star",
        "preset_system": "harmonograph",
        "group": "Classic",
        "params": {
          "renderMode": "line",
          "duration": 40,
          "scale": 0.5,
          "loopDrift": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 100,
              "ampY": 0,
              "phaseX": 90,
              "phaseY": 0,
              "freq": 3,
              "micro": 0.006,
              "damp": 0.0012
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 0,
              "ampY": 100,
              "phaseX": 0,
              "phaseY": 0,
              "freq": 2,
              "micro": 0.006,
              "damp": 0.0012
            }
          ]
        }
      },
      {
        "id": "harmonograph-evolving-snake",
        "name": "Evolving Snake",
        "preset_system": "harmonograph",
        "group": "Evolving",
        "params": {
          "renderMode": "line",
          "duration": 30,
          "scale": 0.45,
          "loopDrift": 0.004,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 130,
              "ampY": 16,
              "phaseX": 90,
              "phaseY": 0,
              "freq": 0.06,
              "micro": 0,
              "damp": 0
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 15,
              "ampY": 15,
              "phaseX": 90,
              "phaseY": 0,
              "freq": 1.1,
              "micro": 0,
              "damp": 0
            }
          ]
        }
      },
      {
        "id": "harmonograph-unison-circle",
        "name": "Unison Circle",
        "preset_system": "harmonograph",
        "group": "Classic",
        "params": {
          "renderMode": "line",
          "duration": 30,
          "scale": 0.55,
          "loopDrift": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 100,
              "ampY": 100,
              "phaseX": 90,
              "phaseY": 0,
              "freq": 2,
              "micro": 0,
              "damp": 0.0006
            }
          ]
        }
      },
      {
        "id": "hyphae-dense-web",
        "name": "Dense Web",
        "preset_system": "hyphae",
        "group": "Complex",
        "params": {
          "sources": 5,
          "steps": 60,
          "branchProb": 0.12,
          "angleVar": 0.5,
          "segLen": 3,
          "maxBranches": 2000
        }
      },
      {
        "id": "hyphae-mycelium",
        "name": "Mycelium",
        "preset_system": "hyphae",
        "group": "Classic",
        "params": {
          "sources": 2,
          "steps": 60,
          "branchProb": 0.05,
          "angleVar": 0.5,
          "segLen": 3,
          "maxBranches": 1000
        }
      },
      {
        "id": "hyphae-sparse-roots",
        "name": "Sparse Roots",
        "preset_system": "hyphae",
        "group": "Organic",
        "params": {
          "sources": 1,
          "steps": 70,
          "branchProb": 0.02,
          "angleVar": 0.6,
          "segLen": 2.5,
          "maxBranches": 600
        }
      },
      {
        "id": "hyphae-tendrils",
        "name": "Tendrils",
        "preset_system": "hyphae",
        "group": "Organic",
        "params": {
          "sources": 2,
          "steps": 80,
          "branchProb": 0.03,
          "angleVar": 0.2,
          "segLen": 4,
          "maxBranches": 800
        }
      },
      {
        "id": "imagesurface-relief-bars",
        "name": "Relief Bars",
        "preset_system": "imageSurface",
        "group": "Classic",
        "params": {
          "mode": "bars",
          "mapType": "height",
          "artworkSize": 146,
          "amplitude": 24,
          "sampleDetail": 64,
          "smoothing": 12,
          "gamma": 0.82,
          "contrast": 18,
          "rotate": -38,
          "tilt": 58,
          "barRows": 13,
          "barColumns": 16,
          "barGap": 2.2,
          "barHeightSteps": 6,
          "showBarBase": true,
          "seeThrough": true
        }
      },
      {
        "id": "lissajous-clover",
        "name": "Clover",
        "preset_system": "lissajous",
        "group": "Geometric",
        "params": {
          "freqX": 3,
          "freqY": 5,
          "phase": 0.5,
          "damping": 0,
          "resolution": 500,
          "scale": 0.8
        }
      },
      {
        "id": "lissajous-damped-knot",
        "name": "Damped Knot",
        "preset_system": "lissajous",
        "group": "Complex",
        "params": {
          "freqX": 7,
          "freqY": 5,
          "phase": 1.5,
          "damping": 0.001,
          "resolution": 600,
          "scale": 0.8
        }
      },
      {
        "id": "lissajous-figure-eight",
        "name": "Figure Eight",
        "preset_system": "lissajous",
        "group": "Classic",
        "params": {
          "freqX": 1,
          "freqY": 2,
          "phase": 1.57,
          "damping": 0,
          "resolution": 300,
          "scale": 0.8
        }
      },
      {
        "id": "lissajous-star",
        "name": "Star",
        "preset_system": "lissajous",
        "group": "Geometric",
        "params": {
          "freqX": 4,
          "freqY": 3,
          "phase": 1,
          "damping": 0,
          "resolution": 500,
          "scale": 0.8
        }
      },
      {
        "id": "lissajous-trefoil",
        "name": "Trefoil",
        "preset_system": "lissajous",
        "group": "Classic",
        "params": {
          "freqX": 1,
          "freqY": 3,
          "phase": 1.57,
          "damping": 0,
          "resolution": 400,
          "scale": 0.8
        }
      },
      {
        "id": "meshtopography-torus-contours",
        "name": "Torus Contours",
        "preset_system": "meshTopography",
        "group": "Classic",
        "params": {
          "sourceMode": "torus",
          "renderMode": "contours",
          "primitiveDetail": 22,
          "primitiveScaleX": 70,
          "primitiveScaleY": 62,
          "primitiveScaleZ": 62,
          "lineCount": 32,
          "planeRotate": 16,
          "planeTilt": 12,
          "contourVisibility": "fullContour",
          "showOutline": true,
          "yaw": -32,
          "pitch": 38
        }
      },
      {
        "id": "pendula-breathing-orbit",
        "name": "Breathing Orbit",
        "preset_system": "pendula",
        "group": "Evolving",
        "params": {
          "renderMode": "line",
          "samples": 6000,
          "duration": 32,
          "scale": 0.55,
          "loopDrift": 0,
          "paperRotation": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 110,
              "ampY": 110,
              "phaseX": 90,
              "phaseY": 0,
              "damp": 0.0004,
              "freq": 2,
              "micro": 0
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 22,
              "ampY": 22,
              "phaseX": 90,
              "phaseY": 0,
              "damp": 0,
              "freq": 2,
              "micro": 0
            }
          ],
          "motion": {
            "sources": [
              {
                "id": "lfo-breath",
                "enabled": true,
                "shape": "sine",
                "syncMode": "sync",
                "rate": 1,
                "depth": 1,
                "phase": 0,
                "polarity": "bi"
              }
            ],
            "edges": [
              {
                "id": "e-breath",
                "sourceId": "lfo-breath",
                "targetParamPath": "pendulums.1.freq",
                "amount": 0.06
              }
            ]
          }
        }
      },
      {
        "id": "pendula-drift-star",
        "name": "Drift Star",
        "preset_system": "pendula",
        "group": "Evolving",
        "params": {
          "renderMode": "line",
          "samples": 7000,
          "duration": 40,
          "scale": 0.5,
          "loopDrift": 0,
          "paperRotation": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 110,
              "ampY": 0,
              "phaseX": 90,
              "phaseY": 0,
              "damp": 0,
              "freq": 3,
              "micro": 0
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 0,
              "ampY": 110,
              "phaseX": 0,
              "phaseY": 0,
              "damp": 0,
              "freq": 2,
              "micro": 0
            }
          ],
          "motion": {
            "sources": [
              {
                "id": "lfo-drift",
                "enabled": true,
                "shape": "saw",
                "syncMode": "sync",
                "rate": 1,
                "depth": 1,
                "phase": 0,
                "polarity": "uni"
              }
            ],
            "edges": [
              {
                "id": "e-drift",
                "sourceId": "lfo-drift",
                "targetParamPath": "loopDrift",
                "amount": 0.02
              }
            ]
          }
        }
      },
      {
        "id": "pendula-pulsing-web",
        "name": "Pulsing Web",
        "preset_system": "pendula",
        "group": "Classic",
        "params": {
          "renderMode": "line",
          "samples": 8000,
          "duration": 44,
          "scale": 0.45,
          "loopDrift": 0.0008,
          "paperRotation": 0.02,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 120,
              "ampY": 0,
              "phaseX": 90,
              "phaseY": 0,
              "damp": 0.0003,
              "freq": 5,
              "micro": 0
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 0,
              "ampY": 120,
              "phaseX": 0,
              "phaseY": 0,
              "damp": 0.0003,
              "freq": 4,
              "micro": 0
            },
            {
              "id": "pend-3",
              "enabled": true,
              "ampX": 36,
              "ampY": 36,
              "phaseX": 45,
              "phaseY": 45,
              "damp": 0.0006,
              "freq": 9,
              "micro": 0
            }
          ],
          "motion": {
            "sources": [],
            "edges": []
          }
        }
      },
      {
        "id": "pendula-tidal-lissajous",
        "name": "Tidal Lissajous",
        "preset_system": "pendula",
        "group": "Evolving",
        "params": {
          "renderMode": "line",
          "samples": 6000,
          "duration": 36,
          "scale": 0.55,
          "loopDrift": 0,
          "paperRotation": 0,
          "pendulums": [
            {
              "id": "pend-1",
              "enabled": true,
              "ampX": 120,
              "ampY": 0,
              "phaseX": 90,
              "phaseY": 0,
              "damp": 0,
              "freq": 3,
              "micro": 0
            },
            {
              "id": "pend-2",
              "enabled": true,
              "ampX": 0,
              "ampY": 90,
              "phaseX": 0,
              "phaseY": 0,
              "damp": 0,
              "freq": 4,
              "micro": 0
            }
          ],
          "motion": {
            "sources": [
              {
                "id": "lfo-tide",
                "enabled": true,
                "shape": "sine",
                "syncMode": "sync",
                "rate": 1,
                "depth": 1,
                "phase": 0,
                "polarity": "bi"
              }
            ],
            "edges": [
              {
                "id": "e-tide-phase",
                "sourceId": "lfo-tide",
                "targetParamPath": "pendulums.1.phaseY",
                "amount": 120
              },
              {
                "id": "e-tide-amp",
                "sourceId": "lfo-tide",
                "targetParamPath": "pendulums.0.ampY",
                "amount": 40
              }
            ]
          }
        }
      },
      {
        "id": "anemone-coronaria",
        "name": "Anemone Coronaria",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "rounded",
          "petalScale": 36,
          "petalWidthRatio": 0.62,
          "count": 7,
          "centerType": "starburst",
          "centerRadius": 8,
          "centerDensity": 40,
          "centerConnectors": true,
          "connectorCount": 32,
          "connectorLength": 12,
          "innerCount": 0,
          "outerCount": 7,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 4,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ]
        }
      },
      {
        "id": "camellia-japonica-pink-perfection",
        "name": "Camellia Japonica Pink Perfection",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "oval",
          "petalScale": 28,
          "petalWidthRatio": 0.55,
          "count": 320,
          "innerCount": 140,
          "outerCount": 200,
          "ringSplit": 0.4,
          "centerType": "disk",
          "centerRadius": 6,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "chrysanthemum-morifolium",
        "name": "Chrysanthemum Morifolium",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "lanceolate",
          "petalScale": 26,
          "petalWidthRatio": 0.25,
          "count": 520,
          "centerType": "disk",
          "centerRadius": 5,
          "innerCount": 220,
          "outerCount": 300,
          "ringSplit": 0.4,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "cosmos-bipinnatus",
        "name": "Cosmos Bipinnatus",
        "preset_system": "petalisDesigner",
        "group": "Geometric",
        "params": {
          "petalProfile": "spatulate",
          "petalScale": 38,
          "petalWidthRatio": 0.45,
          "count": 8,
          "spiralMode": "custom",
          "customAngle": 45,
          "centerType": "dot",
          "centerRadius": 7,
          "innerCount": 0,
          "outerCount": 8,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 4,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ]
        }
      },
      {
        "id": "dahlia-cornel",
        "name": "Dahlia Cornel",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "teardrop",
          "petalScale": 30,
          "petalWidthRatio": 0.5,
          "count": 420,
          "innerCount": 180,
          "outerCount": 260,
          "ringSplit": 0.35,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "dahlia-ivanetti",
        "name": "Dahlia Ivanetti",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "teardrop",
          "petalScale": 32,
          "petalWidthRatio": 0.46,
          "count": 380,
          "innerCount": 160,
          "outerCount": 220,
          "ringSplit": 0.35,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "echeveria-agavoides",
        "name": "Echeveria Agavoides",
        "preset_system": "petalisDesigner",
        "group": "Organic",
        "params": {
          "petalProfile": "dagger",
          "petalScale": 26,
          "petalWidthRatio": 0.38,
          "count": 200,
          "spiralTightness": 1.45,
          "basePinch": 0.2,
          "centerType": "disk",
          "centerRadius": 5,
          "innerCount": 90,
          "outerCount": 110,
          "ringSplit": 0.3,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "fenestraria-aurantiaca",
        "name": "Fenestraria Aurantiaca",
        "preset_system": "petalisDesigner",
        "group": "Organic",
        "params": {
          "petalProfile": "spoon",
          "petalScale": 22,
          "petalWidthRatio": 0.7,
          "count": 14,
          "spiralTightness": 0.8,
          "budMode": true,
          "budRadius": 0.28,
          "centerType": "disk",
          "centerRadius": 4,
          "innerCount": 0,
          "outerCount": 14,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "gardenia-jasminoides",
        "name": "Gardenia Jasminoides",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "oval",
          "petalScale": 32,
          "petalWidthRatio": 0.58,
          "count": 200,
          "innerCount": 80,
          "outerCount": 140,
          "ringSplit": 0.35,
          "centerType": "dome",
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "gerbera-jamesonii",
        "name": "Gerbera Jamesonii",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "lanceolate",
          "petalScale": 34,
          "petalWidthRatio": 0.32,
          "count": 34,
          "centerType": "starburst",
          "centerRadius": 7,
          "centerDensity": 48,
          "innerCount": 0,
          "outerCount": 34,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "hellebore-niger",
        "name": "Helleborus Niger",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "oval",
          "petalScale": 38,
          "petalWidthRatio": 0.7,
          "count": 5,
          "centerType": "dot",
          "centerRadius": 6,
          "innerCount": 0,
          "outerCount": 5,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 5,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ]
        }
      },
      {
        "id": "iris-germanica",
        "name": "Iris Germanica",
        "preset_system": "petalisDesigner",
        "group": "Geometric",
        "params": {
          "petalProfile": "lanceolate",
          "petalScale": 40,
          "petalWidthRatio": 0.4,
          "count": 6,
          "tipTwist": 0.8,
          "rotationJitter": 0,
          "centerType": "disk",
          "centerRadius": 5,
          "innerCount": 3,
          "outerCount": 3,
          "ringSplit": 0.5,
          "ringOffset": 60,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 5,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ],
          "anchorToCenter": "all"
        }
      },
      {
        "id": "lotus-nelumbo-nucifera",
        "name": "Lotus Nelumbo Nucifera",
        "preset_system": "petalisDesigner",
        "group": "Geometric",
        "params": {
          "petalProfile": "spoon",
          "petalScale": 42,
          "petalWidthRatio": 0.65,
          "count": 120,
          "innerCount": 36,
          "outerCount": 90,
          "ringSplit": 0.3,
          "centerType": "disk",
          "centerRadius": 10,
          "centerConnectors": true,
          "connectorCount": 24,
          "connectorLength": 14,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "pachyphytum-compactum",
        "name": "Pachyphytum Compactum",
        "preset_system": "petalisDesigner",
        "group": "Organic",
        "params": {
          "petalProfile": "oval",
          "petalScale": 24,
          "petalWidthRatio": 0.42,
          "count": 160,
          "spiralTightness": 1.2,
          "centerType": "dome",
          "centerRadius": 6,
          "innerCount": 70,
          "outerCount": 90,
          "ringSplit": 0.3,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "plumeria-rubra",
        "name": "Plumeria Rubra",
        "preset_system": "petalisDesigner",
        "group": "Geometric",
        "params": {
          "petalProfile": "oval",
          "petalScale": 46,
          "petalWidthRatio": 0.72,
          "count": 5,
          "spiralMode": "custom",
          "customAngle": 72,
          "centerType": "disk",
          "centerRadius": 9,
          "innerCount": 0,
          "outerCount": 5,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 4,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ]
        }
      },
      {
        "id": "protea-cynaroides",
        "name": "Protea Cynaroides",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "dagger",
          "petalScale": 36,
          "petalWidthRatio": 0.38,
          "count": 280,
          "centerType": "filament",
          "centerRadius": 10,
          "centerDensity": 40,
          "innerCount": 120,
          "outerCount": 160,
          "ringSplit": 0.35,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "ranunculus-asiaticus",
        "name": "Ranunculus Asiaticus",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "oval",
          "petalScale": 26,
          "petalWidthRatio": 0.58,
          "count": 260,
          "innerCount": 120,
          "outerCount": 160,
          "ringSplit": 0.4,
          "centerType": "dome",
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "rosa-chinensis-mutabilis",
        "name": "Rosa Chinensis Mutabilis",
        "preset_system": "petalisDesigner",
        "group": "Complex",
        "params": {
          "petalProfile": "heart",
          "petalScale": 34,
          "petalWidthRatio": 0.6,
          "count": 5,
          "centerSizeMorph": -0.4,
          "centerShapeMorph": 0.4,
          "innerCount": 0,
          "outerCount": 5,
          "ringSplit": 0.45,
          "ringOffset": 0,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 4,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ]
        }
      },
      {
        "id": "tulipa-gesneriana",
        "name": "Tulipa Gesneriana",
        "preset_system": "petalisDesigner",
        "group": "Geometric",
        "params": {
          "petalProfile": "spoon",
          "petalScale": 44,
          "petalWidthRatio": 0.6,
          "count": 6,
          "budMode": true,
          "budRadius": 0.22,
          "centerType": "disk",
          "centerRadius": 5,
          "innerCount": 3,
          "outerCount": 3,
          "ringSplit": 0.5,
          "ringOffset": 60,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0,
          "shadings": [
            {
              "id": "designer-shade-1",
              "enabled": true,
              "type": "vein",
              "target": "both",
              "veinCount": 5,
              "veinReach": 0.6,
              "lineType": "solid",
              "lineSpacing": 1,
              "density": 1,
              "widthX": 100,
              "widthY": 100,
              "posX": 50,
              "posY": 50,
              "gapX": 0,
              "gapY": 0,
              "gapPosX": 50,
              "gapPosY": 50,
              "jitter": 0,
              "lengthJitter": 0,
              "angle": 0
            }
          ],
          "anchorToCenter": "all"
        }
      },
      {
        "id": "zinnia-elegans",
        "name": "Zinnia Elegans",
        "preset_system": "petalisDesigner",
        "group": "Classic",
        "params": {
          "petalProfile": "oval",
          "petalScale": 30,
          "petalWidthRatio": 0.5,
          "count": 240,
          "centerType": "disk",
          "centerRadius": 7,
          "innerCount": 100,
          "outerCount": 140,
          "ringSplit": 0.4,
          "ringOffset": 12,
          "rotationJitter": 0,
          "sizeJitter": 0,
          "countJitter": 0
        }
      },
      {
        "id": "phylla-sunflower",
        "name": "Sunflower",
        "preset_system": "phylla",
        "group": "Classic",
        "params": {
          "count": 500,
          "spacing": 5,
          "angleStr": 137.5,
          "divergence": 1,
          "dotSize": 1,
          "shapeType": "circle"
        }
      },
      {
        "id": "phylla-dense-field",
        "name": "Dense Field",
        "preset_system": "phylla",
        "group": "Complex",
        "params": {
          "count": 1500,
          "spacing": 5,
          "angleStr": 137.5,
          "divergence": 1,
          "dotSize": 0.6,
          "shapeType": "circle"
        }
      },
      {
        "id": "phylla-honeycomb",
        "name": "Honeycomb",
        "preset_system": "phylla",
        "group": "Geometric",
        "params": {
          "count": 400,
          "spacing": 5,
          "angleStr": 137.5,
          "divergence": 0.9,
          "dotSize": 1.5,
          "shapeType": "polygon",
          "sides": 6
        }
      },
      {
        "id": "phylla-pinecone",
        "name": "Pinecone",
        "preset_system": "phylla",
        "group": "Classic",
        "params": {
          "count": 300,
          "spacing": 4,
          "angleStr": 137.5,
          "divergence": 1,
          "dotSize": 1.2,
          "shapeType": "circle"
        }
      },
      {
        "id": "polyhedron-dashed-buckyball",
        "name": "Dashed Buckyball",
        "preset_system": "polyhedron",
        "group": "Classic",
        "params": {
          "solidType": "buckyball",
          "radius": 76,
          "surfaceMode": "all",
          "faceOpacityMode": "seeThrough",
          "showFaces": true,
          "faceBands": 3,
          "showEdges": true,
          "edgeStyle": "dash",
          "edgeSpacing": 10,
          "showVertices": false,
          "bulge": 4,
          "rotate": -22,
          "tilt": 31
        }
      },
      {
        "id": "rainfall-downpour",
        "name": "Downpour",
        "preset_system": "rainfall",
        "group": "Complex",
        "params": {
          "count": 500,
          "traceLength": 180,
          "traceStep": 3,
          "turbulence": 0.4,
          "rainfallAngle": 150
        }
      },
      {
        "id": "rainfall-drizzle",
        "name": "Drizzle",
        "preset_system": "rainfall",
        "group": "Classic",
        "params": {
          "count": 80,
          "traceLength": 60,
          "traceStep": 3,
          "turbulence": 0.1,
          "rainfallAngle": 150
        }
      },
      {
        "id": "rainfall-summer-rain",
        "name": "Summer Rain",
        "preset_system": "rainfall",
        "group": "Classic",
        "params": {
          "count": 200,
          "traceLength": 120,
          "traceStep": 3,
          "turbulence": 0.25,
          "rainfallAngle": 150
        }
      },
      {
        "id": "rainfall-windswept",
        "name": "Windswept",
        "preset_system": "rainfall",
        "group": "Organic",
        "params": {
          "count": 150,
          "traceLength": 130,
          "traceStep": 3,
          "turbulence": 0.3,
          "rainfallAngle": 120,
          "windAngle": 180,
          "windStrength": 0.6
        }
      },
      {
        "id": "rings-ancient-redwood",
        "name": "Ancient Redwood",
        "preset_system": "rings",
        "group": "Classic",
        "params": {
          "rings": 48,
          "gap": 1.05,
          "gapCurveStart": 1.8,
          "gapCurveEnd": 0.6,
          "spacingVariance": 0.5,
          "barkRings": 10,
          "barkGap": 1,
          "breakCount": 6,
          "centerDrift": 0.6,
          "biasStrength": 0.15,
          "biasAngle": 45,
          "rayCount": 80,
          "rayLength": 3.2,
          "rayInnerFraction": 0.1,
          "knotCount": 2,
          "knotIntensity": 0.8,
          "knotSpread": 35,
          "seed": 2266
        }
      },
      {
        "id": "rings-ancient",
        "name": "Ancient",
        "preset_system": "rings",
        "group": "Complex",
        "params": {
          "rings": 40,
          "gap": 1,
          "gapCurveStart": 1.8,
          "gapCurveEnd": 0.6,
          "spacingVariance": 0.5,
          "barkRings": 10,
          "barkGap": 1,
          "breakCount": 6,
          "centerDrift": 0.6,
          "biasStrength": 0.15,
          "biasAngle": 60,
          "rayCount": 80,
          "rayLength": 3,
          "knotCount": 2,
          "knotIntensity": 0.8,
          "crackCount": 3,
          "crackDepth": 0.6,
          "scarCount": 2,
          "scarDepth": 3,
          "seed": 777
        }
      },
      {
        "id": "rings-fresh-cut",
        "name": "Fresh Cut",
        "preset_system": "rings",
        "group": "Geometric",
        "params": {
          "rings": 25,
          "gap": 1.1,
          "gapCurveStart": 1,
          "gapCurveEnd": 1,
          "spacingVariance": 0,
          "barkRings": 3,
          "barkGap": 1.5,
          "breakCount": 0,
          "centerDrift": 0,
          "biasStrength": 0,
          "rayCount": 0,
          "knotCount": 0,
          "seed": 1010
        }
      },
      {
        "id": "rings-old-growth-oak",
        "name": "Old Growth Oak",
        "preset_system": "rings",
        "group": "Classic",
        "params": {
          "rings": 32,
          "gap": 1.1,
          "gapCurveStart": 1.6,
          "gapCurveEnd": 0.7,
          "spacingVariance": 0.4,
          "barkRings": 6,
          "barkGap": 1.5,
          "breakCount": 4,
          "centerDrift": 0.4,
          "biasStrength": 0.12,
          "biasAngle": 210,
          "rayCount": 45,
          "rayLength": 2.8,
          "rayInnerFraction": 0.12,
          "knotCount": 1,
          "knotIntensity": 0.7,
          "knotSpread": 28,
          "seed": 3714
        }
      },
      {
        "id": "rings-pine-cross-section",
        "name": "Pine Cross-Section",
        "preset_system": "rings",
        "group": "Classic",
        "params": {
          "rings": 22,
          "gap": 1.15,
          "gapCurveStart": 1.4,
          "gapCurveEnd": 0.85,
          "spacingVariance": 0.25,
          "barkRings": 4,
          "barkGap": 2,
          "breakCount": 0,
          "centerDrift": 0.2,
          "biasStrength": 0.08,
          "biasAngle": 160,
          "rayCount": 0,
          "rayLength": 2.5,
          "rayInnerFraction": 0.15,
          "knotCount": 0,
          "knotIntensity": 0.6,
          "knotSpread": 30,
          "seed": 8821
        }
      },
      {
        "id": "shapepack-bubbles",
        "name": "Bubbles",
        "preset_system": "shapePack",
        "group": "Classic",
        "params": {
          "shape": "circle",
          "count": 300,
          "minR": 3,
          "maxR": 18,
          "padding": 2,
          "attempts": 300,
          "segments": 32
        }
      },
      {
        "id": "shapepack-confetti",
        "name": "Confetti",
        "preset_system": "shapePack",
        "group": "Complex",
        "params": {
          "shape": "circle",
          "count": 800,
          "minR": 1,
          "maxR": 25,
          "padding": 1,
          "attempts": 500,
          "segments": 24
        }
      },
      {
        "id": "shapepack-hexagonal-mosaic",
        "name": "Hexagonal Mosaic",
        "preset_system": "shapePack",
        "group": "Geometric",
        "params": {
          "shape": "polygon",
          "count": 200,
          "minR": 6,
          "maxR": 12,
          "padding": 1,
          "attempts": 300,
          "segments": 6
        }
      },
      {
        "id": "shapepack-pebble-beach",
        "name": "Pebble Beach",
        "preset_system": "shapePack",
        "group": "Organic",
        "params": {
          "shape": "circle",
          "count": 500,
          "minR": 2,
          "maxR": 10,
          "padding": 1,
          "attempts": 400,
          "segments": 24
        }
      },
      {
        "id": "spiral-galaxy",
        "name": "Galaxy",
        "preset_system": "spiral",
        "group": "Complex",
        "params": {
          "loops": 35,
          "res": 150,
          "startR": 2,
          "pulseAmp": 2,
          "pulseFreq": 2
        }
      },
      {
        "id": "spiral-pulsing-vortex",
        "name": "Pulsing Vortex",
        "preset_system": "spiral",
        "group": "Organic",
        "params": {
          "loops": 10,
          "res": 120,
          "startR": 5,
          "pulseAmp": 8,
          "pulseFreq": 3
        }
      },
      {
        "id": "spiral-simple",
        "name": "Simple Spiral",
        "preset_system": "spiral",
        "group": "Classic",
        "params": {
          "loops": 5,
          "res": 100,
          "startR": 5,
          "pulseAmp": 0
        }
      },
      {
        "id": "spiral-tight-coil",
        "name": "Tight Coil",
        "preset_system": "spiral",
        "group": "Geometric",
        "params": {
          "loops": 20,
          "res": 120,
          "startR": 2,
          "pulseAmp": 0
        }
      },
      {
        "id": "spiral3d-default",
        "name": "Default",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "label": "3D Spiral",
          "is3d": true,
          "preset": "spiral3d-default",
          "shape": "sphere",
          "sphereRadius": 65,
          "baseRadius": 68,
          "coneHeight": 136,
          "cylinderRadius": 58,
          "cylinderHeight": 156,
          "ellipsoidEquatorRadius": 76,
          "ellipsoidPolarRadius": 52,
          "surfaceMode": "seeThrough",
          "outlineMode": "none",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 18,
          "twistTurns": 6,
          "lineCount": 16,
          "dotSpacing": 14,
          "dotSizeStart": 4,
          "dotSizeMiddle": 4,
          "dotSizeEnd": 4,
          "startLongitude": 0,
          "yaw": 0,
          "pitch": 30,
          "roll": 0,
          "curveResolution": 900,
          "projection": "orthographic",
          "cameraDistance": 620,
          "focalLength": 520,
          "depthCue": "off",
          "depthCueStrength": 60,
          "emphasizeOutline": false,
          "outlineWeight": 2,
          "showCreases": false,
          "creaseAngle": 35,
          "hiddenLineMode": "backface",
          "depthBias": 0.5,
          "hatchEnable": false,
          "lightAzimuth": 135,
          "lightElevation": 45,
          "hatchAngle": 45,
          "hatchSpacing": 6,
          "crossHatch": false,
          "smoothing": 0,
          "simplify": 0,
          "curves": false
        }
      },
      {
        "id": "spiral3d-capsule-wrap",
        "name": "Capsule Wrap",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "shape": "capsule",
          "capsuleRadius": 48,
          "capsuleHeight": 132,
          "surfaceMode": "front",
          "outlineMode": "outline",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 36,
          "yaw": 0,
          "pitch": 28,
          "roll": 0,
          "curveResolution": 1100
        }
      },
      {
        "id": "user-spiral3d-1781359265086",
        "name": "Simple Sphere",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "label": "3D Spiral",
          "is3d": true,
          "preset": "spiral3d-spherical-wrap",
          "shape": "sphere",
          "sphereRadius": 52,
          "baseRadius": 68,
          "coneHeight": 136,
          "cylinderRadius": 58,
          "cylinderHeight": 156,
          "ellipsoidEquatorRadius": 76,
          "ellipsoidPolarRadius": 52,
          "surfaceMode": "front",
          "outlineMode": "none",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 18,
          "twistTurns": 6,
          "lineCount": 16,
          "dotSpacing": 14,
          "dotSizeStart": 4,
          "dotSizeMiddle": 4,
          "dotSizeEnd": 4,
          "startLongitude": 0,
          "yaw": 0,
          "pitch": 30,
          "roll": 0,
          "curveResolution": 900,
          "projection": "orthographic",
          "cameraDistance": 620,
          "focalLength": 520,
          "smoothing": 0,
          "simplify": 0,
          "curves": false
        }
      },
      {
        "id": "spiral3d-sphere",
        "name": "Sphere",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "label": "3D Spiral",
          "is3d": true,
          "preset": "spiral3d-sphere",
          "shape": "sphere",
          "sphereRadius": 64,
          "baseRadius": 68,
          "coneHeight": 136,
          "cylinderRadius": 58,
          "cylinderHeight": 156,
          "ellipsoidEquatorRadius": 76,
          "ellipsoidPolarRadius": 52,
          "surfaceMode": "seeThrough",
          "outlineMode": "none",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 18,
          "twistTurns": 6,
          "lineCount": 16,
          "dotSpacing": 14,
          "dotSizeStart": 4,
          "dotSizeMiddle": 4,
          "dotSizeEnd": 4,
          "startLongitude": 0,
          "yaw": 0,
          "pitch": 30,
          "roll": 0,
          "curveResolution": 900,
          "projection": "orthographic",
          "cameraDistance": 620,
          "focalLength": 520,
          "smoothing": 0,
          "simplify": 0,
          "curves": false
        }
      },
      {
        "id": "user-spiral3d-1781359333969",
        "name": "Spherical Wrap",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "label": "3D Spiral",
          "is3d": true,
          "preset": "user-spiral3d-1781359265086",
          "shape": "sphere",
          "sphereRadius": 62,
          "baseRadius": 68,
          "coneHeight": 136,
          "cylinderRadius": 58,
          "cylinderHeight": 156,
          "ellipsoidEquatorRadius": 76,
          "ellipsoidPolarRadius": 52,
          "surfaceMode": "seeThrough",
          "outlineMode": "none",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 18,
          "twistTurns": 6,
          "lineCount": 16,
          "dotSpacing": 14,
          "dotSizeStart": 4,
          "dotSizeMiddle": 4,
          "dotSizeEnd": 4,
          "startLongitude": 0,
          "yaw": 0,
          "pitch": 30,
          "roll": 0,
          "curveResolution": 900,
          "projection": "orthographic",
          "cameraDistance": 620,
          "focalLength": 520,
          "smoothing": 0,
          "simplify": 0,
          "curves": false
        }
      },
      {
        "id": "spiral3d-torus-coil",
        "name": "Torus Coil",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "shape": "torus",
          "torusRingRadius": 68,
          "torusTubeRadius": 28,
          "surfaceMode": "front",
          "outlineMode": "outline",
          "wrapType": "spiral",
          "renderStyle": "line",
          "turns": 90,
          "yaw": -18,
          "pitch": 42,
          "roll": 0,
          "curveResolution": 1600
        }
      },
      {
        "id": "spiral3d-twisted-cone",
        "name": "Twisted Cone",
        "preset_system": "spiral3d",
        "group": "Classic",
        "params": {
          "shape": "cone",
          "baseRadius": 78,
          "coneHeight": 146,
          "surfaceMode": "seeThrough",
          "outlineMode": "outline",
          "wrapType": "twistedLines",
          "renderStyle": "line",
          "twistTurns": 7.5,
          "lineCount": 20,
          "yaw": -12,
          "pitch": 34,
          "roll": 0,
          "curveResolution": 540
        }
      },
      {
        "id": "spirograph-inner-gear-bloom",
        "name": "Inner Gear Bloom",
        "preset_system": "spirograph",
        "group": "Classic",
        "params": {
          "mainShape": "polygon",
          "mainWidth": 148,
          "mainHeight": 148,
          "mainPoints": 7,
          "mainTeeth": 252,
          "gearShape": "oval",
          "gearTeeth": 73,
          "gearAspectX": 120,
          "gearAspectY": 78,
          "penAngle": 18,
          "penOffset": 92,
          "rollMode": "inside",
          "curveResolution": 1000
        }
      },
      {
        "id": "svg-distort-cross-hatch",
        "name": "Cross Hatch",
        "preset_system": "svgDistort",
        "group": "Geometric",
        "params": {
          "showOutlines": true,
          "fillMode": "crosshatch",
          "fillDensity": 4,
          "autoFit": true,
          "scale": 1,
          "noises": []
        }
      },
      {
        "id": "svg-distort-loose-fill",
        "name": "Loose Fill",
        "preset_system": "svgDistort",
        "group": "Organic",
        "params": {
          "showOutlines": true,
          "fillMode": "hatch",
          "fillDensity": 2,
          "autoFit": true,
          "scale": 1,
          "noises": []
        }
      },
      {
        "id": "svg-distort-hatched",
        "name": "SVG Hatch Fill + Noise",
        "preset_system": "svgDistort",
        "group": "Classic",
        "params": {
          "showOutlines": true,
          "fillMode": "hatch",
          "fillDensity": 6,
          "autoFit": true,
          "scale": 1,
          "noises": [
            {
              "id": "noise-1",
              "enabled": true,
              "type": "simplex",
              "blend": "add",
              "amplitude": 3,
              "zoom": 0.015,
              "freq": 1,
              "angle": 0,
              "shiftX": 0,
              "shiftY": 0,
              "tileMode": "off",
              "tilePadding": 0,
              "patternScale": 1,
              "warpStrength": 1,
              "cellularScale": 1,
              "cellularJitter": 1,
              "stepsCount": 5,
              "seed": 0,
              "octaves": 2,
              "lacunarity": 2,
              "gain": 0.5,
              "noiseStyle": "linear",
              "noiseThreshold": 0,
              "imageWidth": 1,
              "imageHeight": 1,
              "microFreq": 0,
              "imageInvertColor": false,
              "imageInvertOpacity": false,
              "imageId": "",
              "imageName": "",
              "imagePreview": "",
              "imageAlgo": "luma",
              "imageEffects": []
            }
          ]
        }
      },
      {
        "id": "svg-distort-plain",
        "name": "SVG Plain Import",
        "preset_system": "svgDistort",
        "group": "Classic",
        "params": {
          "showOutlines": true,
          "fillMode": "none",
          "autoFit": true,
          "scale": 1,
          "noises": []
        }
      },
      {
        "id": "terrain-default",
        "name": "Default",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {
          "label": "Terrain",
          "is3d": true,
          "preset": "terrain-default",
          "perspectiveMode": "two-point",
          "horizonHeight": 50,
          "vanishingPointX": 50,
          "vpLeftX": 0,
          "vpRightX": 100,
          "isoAngle": 30,
          "depthCompression": 36,
          "depthScale": 80,
          "depthSlices": 33,
          "xResolution": 210,
          "occlusion": true,
          "mountainAmplitude": 22,
          "mountainFrequency": 0.008,
          "mountainOctaves": 5,
          "mountainLacunarity": 1.9,
          "mountainGain": 0.5,
          "peakSharpness": 2,
          "valleyCount": 2,
          "valleyDepth": 30,
          "valleyWidth": 20,
          "valleyShape": 0.4,
          "valleyMeander": 40,
          "riversEnabled": false,
          "riverCount": 2,
          "riverWidth": 3,
          "riverDepth": 8,
          "riverMeander": 50,
          "oceansEnabled": false,
          "waterLevel": 20,
          "drawCoastline": true,
          "noises": [
            {
              "enabled": true,
              "type": "simplex",
              "blend": "add",
              "amplitude": 0,
              "zoom": 0.01,
              "freq": 1,
              "angle": 0,
              "shiftX": 0,
              "shiftY": 0,
              "tileMode": "off",
              "tilePadding": 0,
              "patternScale": 1,
              "warpStrength": 1,
              "cellularScale": 1,
              "cellularJitter": 1,
              "stepsCount": 5,
              "seed": 0,
              "noiseStyle": "linear",
              "noiseThreshold": 0,
              "imageWidth": 1,
              "imageHeight": 1,
              "microFreq": 0,
              "imageInvertColor": false,
              "imageInvertOpacity": false,
              "imageId": "",
              "imageName": "",
              "imagePreview": "",
              "imageAlgo": "luma",
              "imageEffects": [
                {
                  "id": "effect-1",
                  "enabled": true,
                  "mode": "luma",
                  "imageBrightness": 0,
                  "imageLevelsLow": 0,
                  "imageLevelsHigh": 1,
                  "imageEmbossStrength": 1,
                  "imageSharpenAmount": 1,
                  "imageSharpenRadius": 1,
                  "imageMedianRadius": 1,
                  "imageGamma": 1,
                  "imageContrast": 1,
                  "imageSolarize": 0.5,
                  "imagePixelate": 12,
                  "imageDither": 0.5,
                  "imageThreshold": 0.5,
                  "imagePosterize": 5,
                  "imageBlur": 0,
                  "imageBlurRadius": 0,
                  "imageBlurStrength": 1,
                  "imageEdgeBlur": 0,
                  "imageHighpassRadius": 1,
                  "imageHighpassStrength": 1,
                  "imageLowpassRadius": 2,
                  "imageLowpassStrength": 0.6,
                  "imageVignetteStrength": 0.4,
                  "imageVignetteRadius": 0.85,
                  "imageCurveStrength": 0.4,
                  "imageBandCenter": 0.5,
                  "imageBandWidth": 0.3
                }
              ],
              "imageThreshold": 0.5,
              "imagePosterize": 5,
              "imageBlur": 0,
              "imageBlurRadius": 0,
              "imageBlurStrength": 1,
              "imageBrightness": 0,
              "imageLevelsLow": 0,
              "imageLevelsHigh": 1,
              "imageEmbossStrength": 1,
              "imageSharpenAmount": 1,
              "imageSharpenRadius": 1,
              "imageMedianRadius": 1,
              "imageGamma": 1,
              "imageContrast": 1,
              "imageSolarize": 0.5,
              "imagePixelate": 12,
              "imageDither": 0.5,
              "polygonZoomReference": 0.01,
              "polygonRadius": 2,
              "polygonSides": 6,
              "polygonRotation": 0,
              "polygonOutline": 0,
              "polygonEdgeRadius": 0,
              "id": "noise-1"
            }
          ],
          "smoothing": 0,
          "simplify": 0,
          "curves": true
        }
      },
      {
        "id": "terrain-alpine",
        "name": "Alpine Range",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {
          "perspectiveMode": "one-point",
          "horizonHeight": 45,
          "depthCompression": 70,
          "depthSlices": 100,
          "xResolution": 280,
          "mountainAmplitude": 65,
          "mountainFrequency": 0.012,
          "mountainOctaves": 6,
          "mountainGain": 0.55,
          "peakSharpness": 3,
          "valleyCount": 3,
          "valleyDepth": 45,
          "valleyWidth": 18,
          "valleyShape": 0.7,
          "valleyMeander": 55,
          "riversEnabled": false,
          "oceansEnabled": false
        }
      },
      {
        "id": "terrain-archipelago",
        "name": "Archipelago",
        "preset_system": "terrain",
        "group": "Organic",
        "params": {
          "perspectiveMode": "one-point",
          "horizonHeight": 50,
          "depthCompression": 60,
          "depthSlices": 90,
          "xResolution": 260,
          "mountainAmplitude": 35,
          "mountainFrequency": 0.011,
          "mountainOctaves": 4,
          "peakSharpness": 1.5,
          "valleyCount": 4,
          "valleyDepth": 40,
          "valleyWidth": 22,
          "valleyShape": 0.6,
          "valleyMeander": 60,
          "riversEnabled": false,
          "oceansEnabled": true,
          "waterLevel": 32,
          "drawCoastline": true
        }
      },
      {
        "id": "terrain-canyon-mesa",
        "name": "Canyon Mesa",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {
          "perspectiveMode": "one-point",
          "horizonHeight": 50,
          "depthCompression": 75,
          "depthSlices": 90,
          "xResolution": 260,
          "mountainAmplitude": 50,
          "mountainFrequency": 0.005,
          "mountainOctaves": 4,
          "mountainGain": 0.65,
          "peakSharpness": 1,
          "valleyCount": 2,
          "valleyDepth": 60,
          "valleyWidth": 14,
          "valleyShape": 0.05,
          "valleyMeander": 30,
          "riversEnabled": true,
          "riverCount": 1,
          "riverWidth": 4,
          "riverDepth": 18,
          "riverMeander": 65,
          "oceansEnabled": false
        }
      },
      {
        "id": "terrain-river-delta",
        "name": "River Delta",
        "preset_system": "terrain",
        "group": "Organic",
        "params": {
          "perspectiveMode": "one-point",
          "horizonHeight": 55,
          "depthCompression": 55,
          "depthSlices": 80,
          "xResolution": 240,
          "mountainAmplitude": 30,
          "mountainFrequency": 0.007,
          "mountainOctaves": 4,
          "mountainGain": 0.45,
          "peakSharpness": 1.3,
          "valleyCount": 2,
          "valleyDepth": 35,
          "valleyWidth": 25,
          "valleyShape": 0.85,
          "valleyMeander": 60,
          "riversEnabled": true,
          "riverCount": 4,
          "riverWidth": 3,
          "riverDepth": 10,
          "riverMeander": 75,
          "oceansEnabled": true,
          "waterLevel": 18,
          "drawCoastline": true
        }
      },
      {
        "id": "terrain-rolling-hills",
        "name": "Rolling Hills",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {
          "perspectiveMode": "one-point",
          "horizonHeight": 55,
          "depthCompression": 50,
          "depthSlices": 70,
          "xResolution": 220,
          "mountainAmplitude": 25,
          "mountainFrequency": 0.006,
          "mountainOctaves": 3,
          "mountainGain": 0.4,
          "peakSharpness": 1.2,
          "valleyCount": 1,
          "valleyDepth": 15,
          "valleyWidth": 35,
          "valleyShape": 0.9,
          "valleyMeander": 25,
          "riversEnabled": false,
          "oceansEnabled": false
        }
      },
      {
        "id": "terrain-tundra-flats",
        "name": "Tundra Flats",
        "preset_system": "terrain",
        "group": "Classic",
        "params": {
          "perspectiveMode": "orthographic",
          "depthScale": 100,
          "depthSlices": 60,
          "xResolution": 240,
          "mountainAmplitude": 18,
          "mountainFrequency": 0.005,
          "mountainOctaves": 3,
          "mountainGain": 0.4,
          "peakSharpness": 1.4,
          "valleyCount": 0,
          "riversEnabled": false,
          "oceansEnabled": false
        }
      },
      {
        "id": "topo-mountain-range",
        "name": "Mountain Range",
        "preset_system": "topo",
        "group": "Classic",
        "params": {
          "resolution": 120,
          "levels": 30,
          "sensitivity": 1,
          "mappingMode": "marching"
        }
      },
      {
        "id": "topo-contour-survey",
        "name": "Contour Survey",
        "preset_system": "topo",
        "group": "Geometric",
        "params": {
          "resolution": 160,
          "levels": 40,
          "sensitivity": 0.8,
          "mappingMode": "marching"
        }
      },
      {
        "id": "topo-island",
        "name": "Island",
        "preset_system": "topo",
        "group": "Complex",
        "params": {
          "resolution": 200,
          "levels": 55,
          "sensitivity": 1.2,
          "mappingMode": "bezier"
        }
      },
      {
        "id": "topo-rolling-plains",
        "name": "Rolling Plains",
        "preset_system": "topo",
        "group": "Organic",
        "params": {
          "resolution": 80,
          "levels": 12,
          "sensitivity": 1.8,
          "mappingMode": "smooth"
        }
      },
      {
        "id": "wavetable-rolling-hills",
        "name": "Rolling Hills",
        "preset_system": "wavetable",
        "group": "Classic",
        "params": {
          "lineStructure": "horizontal",
          "lines": 130,
          "gap": 1,
          "edgeFade": 0
        }
      },
      {
        "id": "wavetable-user-billowing-fabric",
        "name": "Billowing Fabric",
        "preset_system": "wavetable",
        "group": "Complex",
        "params": {
          "preset": "user-wavetable-1780851597059",
          "lineStructure": "horizontal",
          "lines": 158,
          "noiseType": "simplex",
          "noiseImageId": "",
          "noiseImageName": "",
          "noises": [
            {
              "enabled": true,
              "type": "radial",
              "blend": "add",
              "amplitude": 6.6,
              "zoom": 0.01,
              "freq": 1,
              "angle": 0,
              "shiftX": 0,
              "shiftY": 0.66,
              "tileMode": "off",
              "tilePadding": 0,
              "patternScale": 0.9,
              "warpStrength": 1,
              "cellularScale": 1,
              "cellularJitter": 1,
              "stepsCount": 5,
              "seed": 0,
              "noiseStyle": "linear",
              "noiseThreshold": 0,
              "imageWidth": 1,
              "imageHeight": 1,
              "microFreq": 0,
              "imageInvertColor": false,
              "imageInvertOpacity": false,
              "imageId": "",
              "imageName": "",
              "imagePreview": "",
              "imageAlgo": "luma",
              "imageEffects": [
                {
                  "id": "effect-1",
                  "enabled": true,
                  "mode": "luma",
                  "imageBrightness": 0,
                  "imageLevelsLow": 0,
                  "imageLevelsHigh": 1,
                  "imageEmbossStrength": 1,
                  "imageSharpenAmount": 1,
                  "imageSharpenRadius": 1,
                  "imageMedianRadius": 1,
                  "imageGamma": 1,
                  "imageContrast": 1,
                  "imageSolarize": 0.5,
                  "imagePixelate": 12,
                  "imageDither": 0.5,
                  "imageThreshold": 0.5,
                  "imagePosterize": 5,
                  "imageBlur": 0,
                  "imageBlurRadius": 0,
                  "imageBlurStrength": 1,
                  "imageEdgeBlur": 0,
                  "imageHighpassRadius": 1,
                  "imageHighpassStrength": 1,
                  "imageLowpassRadius": 2,
                  "imageLowpassStrength": 0.6,
                  "imageVignetteStrength": 0.4,
                  "imageVignetteRadius": 0.85,
                  "imageCurveStrength": 0.4,
                  "imageBandCenter": 0.5,
                  "imageBandWidth": 0.3
                }
              ],
              "imageThreshold": 0.5,
              "imagePosterize": 5,
              "imageBlur": 0,
              "imageBlurRadius": 0,
              "imageBlurStrength": 1,
              "imageBrightness": 0,
              "imageLevelsLow": 0,
              "imageLevelsHigh": 1,
              "imageEmbossStrength": 1,
              "imageSharpenAmount": 1,
              "imageSharpenRadius": 1,
              "imageMedianRadius": 1,
              "imageGamma": 1,
              "imageContrast": 1,
              "imageSolarize": 0.5,
              "imagePixelate": 12,
              "imageDither": 0.5,
              "polygonZoomReference": 0.02,
              "polygonRadius": 2,
              "polygonSides": 6,
              "polygonRotation": 0,
              "polygonOutline": 0,
              "polygonEdgeRadius": 0,
              "id": "noise-1"
            }
          ],
          "imageAlgo": "luma",
          "imageThreshold": 0.5,
          "imagePosterize": 5,
          "imageBlur": 0,
          "amplitude": 9,
          "zoom": 0.02,
          "tilt": 0.5,
          "gap": 0.7,
          "freq": 1,
          "lineOffset": 175,
          "continuity": "none",
          "dampenExtremes": false,
          "overlapPadding": 0,
          "flatCaps": false,
          "edgeFadeMode": "both",
          "edgeFade": 0,
          "edgeFadeThreshold": 0,
          "edgeFadeFeather": 0,
          "noiseAngle": 0,
          "verticalFade": 25,
          "verticalFadeThreshold": 0,
          "verticalFadeFeather": 0,
          "verticalFadeMode": "both",
          "smoothing": 0,
          "simplify": 0,
          "curves": true
        }
      },
      {
        "id": "wavetable-interference",
        "name": "Interference",
        "preset_system": "wavetable",
        "group": "Geometric",
        "params": {
          "lineStructure": "horizontal-vertical",
          "lines": 110,
          "gap": 1,
          "edgeFade": 20,
          "edgeFadeMode": "both"
        }
      },
      {
        "id": "wavetable-ripple-field",
        "name": "Ripple Field",
        "preset_system": "wavetable",
        "group": "Classic",
        "params": {
          "lineStructure": "vertical",
          "lines": 100,
          "lineOffset": 135,
          "gap": 1
        }
      },
      {
        "id": "wavetable-storm-waves",
        "name": "Storm Waves",
        "preset_system": "wavetable",
        "group": "Complex",
        "params": {
          "lineStructure": "vertical",
          "lines": 150,
          "lineOffset": 135,
          "verticalFade": 25,
          "verticalFadeMode": "both"
        }
      }
    ]);
})();
