(() => {
  'use strict';
  // Auto-generated by scripts/build-user-presets.js — do not edit manually.
  // To add presets: drop .vectura files into user-presets/<algorithm>/ (the
  // directory name is the layer type), then run: npm run user-presets:bundle
  const Vectura = (window.Vectura = window.Vectura || {});
  if (!Array.isArray(Vectura.PRESETS)) Vectura.PRESETS = [];
  Vectura.PRESETS.push(...[]);
})();
